/**
 * AVS Gold ERP — Platform-Provided Central Email Service
 * 
 * Master Service providing:
 * 1. Default AVS platform email sender identity for all tenant communications.
 * 2. Mandatory, standardized AVS branded footer injection on every outgoing email.
 * 3. Centralized email template rendering with token interpolation.
 * 4. Audit logging and outbox delivery tracking.
 */

import { dataProvider as supabase } from "@/lib/providers/data-provider";

export interface PlatformEmailSenderConfig {
  fromEmail: string;
  fromName: string;
  replyTo: string;
  smtpHost: string;
  smtpPort: number;
  smtpUser?: string;
  supportPhone?: string;
  supportEmail?: string;
  portalUrl?: string;
  legalDisclaimer?: string;
}

export interface EmailTemplateConfig {
  id: string;
  templateCode: string;
  templateName: string;
  category: "billing" | "subscription" | "account" | "customer" | "system";
  subject: string;
  bodyHtml: string;
  availableTokens: string[];
  isActive: boolean;
  updatedAt: string;
}

export interface EmailDeliveryRecord {
  id: string;
  recipient: string;
  sender: string;
  tenantId?: string;
  tenantName?: string;
  templateCode?: string;
  documentRef?: string;
  messageType: string;
  subject: string;
  status: "sent" | "failed" | "queued";
  providerResponse?: string;
  retryCount: number;
  createdAt: string;
}

const DEFAULT_SENDER_CONFIG: PlatformEmailSenderConfig = {
  fromEmail: "notifications@arivahly.in",
  fromName: "AVS Gold ERP Platform",
  replyTo: "support@arivahly.in",
  smtpHost: "smtp.hostinger.com",
  smtpPort: 465,
  supportPhone: "+91 98765 43210",
  supportEmail: "support@arivahly.in",
  portalUrl: "https://erp.arivahly.in",
  legalDisclaimer: "This is an official transactional message generated by AVS Gold ERP. Please do not reply directly to automated dispatch addresses.",
};

const DEFAULT_EMAIL_TEMPLATES: Record<string, EmailTemplateConfig> = {
  tenant_welcome: {
    id: "tmpl_tenant_welcome",
    templateCode: "tenant_welcome",
    templateName: "Tenant Account Provisioned & Welcome",
    category: "account",
    subject: "Welcome to AVS Gold ERP — Your Account has been Provisioned for {{tenant_name}}",
    bodyHtml: `
      <div style="font-family: Arial, sans-serif; color: #1e293b; line-height: 1.6;">
        <h2 style="color: #d97706; margin-bottom: 8px;">Welcome to AVS Gold ERP</h2>
        <p>Dear <strong>{{admin_name}}</strong>,</p>
        <p>Your tenant workspace for <strong>{{tenant_name}}</strong> has been successfully created and configured on the platform.</p>
        
        <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin: 20px 0;">
          <h3 style="margin-top: 0; color: #0f172a; font-size: 14px; text-transform: uppercase;">Workspace Credentials & Details</h3>
          <p style="margin: 4px 0;"><strong>Tenant Slug:</strong> {{tenant_slug}}</p>
          <p style="margin: 4px 0;"><strong>Admin Login:</strong> {{admin_email}}</p>
          <p style="margin: 4px 0;"><strong>Selected Plan:</strong> {{plan_name}}</p>
          <p style="margin: 4px 0;"><strong>Main Branch:</strong> {{branch_name}}</p>
          <p style="margin: 4px 0;"><strong>Login Portal:</strong> <a href="{{login_url}}" style="color: #d97706;">{{login_url}}</a></p>
        </div>

        <p>You can now sign in to your workspace, setup Karigar artisans, manage inventory vaults, and issue custom job cards.</p>
        <div style="margin: 24px 0;">
          <a href="{{login_url}}" style="background: #d97706; color: #ffffff; text-decoration: none; padding: 10px 20px; border-radius: 4px; font-weight: bold; display: inline-block;">Sign In to AVS ERP</a>
        </div>
      </div>
    `,
    availableTokens: ["{{tenant_name}}", "{{admin_name}}", "{{admin_email}}", "{{tenant_slug}}", "{{plan_name}}", "{{branch_name}}", "{{login_url}}"],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  invoice: {
    id: "tmpl_invoice",
    templateCode: "invoice",
    templateName: "Tax Invoice & Payment Receipt",
    category: "billing",
    subject: "Tax Invoice {{invoice_number}} from {{tenant_name}}",
    bodyHtml: `
      <div style="font-family: Arial, sans-serif; color: #1e293b; line-height: 1.6;">
        <h2 style="color: #d97706; margin-bottom: 8px;">Tax Invoice from {{tenant_name}}</h2>
        <p>Dear <strong>{{customer_name}}</strong>,</p>
        <p>Please find attached your invoice <strong>{{invoice_number}}</strong> for the amount of <strong>₹{{invoice_total}}</strong>.</p>
        
        <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin: 20px 0;">
          <p style="margin: 4px 0;"><strong>Invoice Number:</strong> {{invoice_number}}</p>
          <p style="margin: 4px 0;"><strong>Date:</strong> {{invoice_date}}</p>
          <p style="margin: 4px 0;"><strong>Total Amount:</strong> ₹{{invoice_total}}</p>
          <p style="margin: 4px 0;"><strong>Payment Status:</strong> {{payment_status}}</p>
        </div>

        <p>Thank you for your business. Please contact us if you have any questions.</p>
      </div>
    `,
    availableTokens: ["{{tenant_name}}", "{{customer_name}}", "{{invoice_number}}", "{{invoice_date}}", "{{invoice_total}}", "{{payment_status}}"],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  quotation: {
    id: "tmpl_quotation",
    templateCode: "quotation",
    templateName: "Subscription / Order Quotation",
    category: "billing",
    subject: "Quotation {{quotation_number}} from {{tenant_name}}",
    bodyHtml: `
      <div style="font-family: Arial, sans-serif; color: #1e293b; line-height: 1.6;">
        <h2 style="color: #d97706; margin-bottom: 8px;">Quotation {{quotation_number}}</h2>
        <p>Dear <strong>{{customer_name}}</strong>,</p>
        <p>Thank you for your interest. Please find details of your quotation below:</p>
        
        <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin: 20px 0;">
          <p style="margin: 4px 0;"><strong>Quotation No:</strong> {{quotation_number}}</p>
          <p style="margin: 4px 0;"><strong>Estimated Total:</strong> ₹{{quotation_total}}</p>
          <p style="margin: 4px 0;"><strong>Validity:</strong> {{valid_until}}</p>
        </div>
      </div>
    `,
    availableTokens: ["{{tenant_name}}", "{{customer_name}}", "{{quotation_number}}", "{{quotation_total}}", "{{valid_until}}"],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  payment_success: {
    id: "tmpl_payment_success",
    templateCode: "payment_success",
    templateName: "Payment Successful Confirmation",
    category: "billing",
    subject: "Payment Confirmed: ₹{{amount}} for {{tenant_name}}",
    bodyHtml: `
      <div style="font-family: Arial, sans-serif; color: #1e293b; line-height: 1.6;">
        <h2 style="color: #10b981; margin-bottom: 8px;">Payment Successful</h2>
        <p>We have successfully received your payment of <strong>₹{{amount}}</strong> for <strong>{{plan_name}}</strong>.</p>
        
        <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin: 20px 0;">
          <p style="margin: 4px 0;"><strong>Transaction Ref:</strong> {{payment_id}}</p>
          <p style="margin: 4px 0;"><strong>Amount Paid:</strong> ₹{{amount}}</p>
          <p style="margin: 4px 0;"><strong>Subscription Renews:</strong> {{renewal_date}}</p>
        </div>
      </div>
    `,
    availableTokens: ["{{tenant_name}}", "{{amount}}", "{{plan_name}}", "{{payment_id}}", "{{renewal_date}}"],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  subscription_renewal: {
    id: "tmpl_subscription_renewal",
    templateCode: "subscription_renewal",
    templateName: "Subscription Renewal Reminder",
    category: "subscription",
    subject: "Subscription Renewal Notice for {{tenant_name}} (Plan: {{plan_name}})",
    bodyHtml: `
      <div style="font-family: Arial, sans-serif; color: #1e293b; line-height: 1.6;">
        <h2 style="color: #d97706; margin-bottom: 8px;">Subscription Renewal Notice</h2>
        <p>Your subscription for <strong>{{tenant_name}}</strong> on the <strong>{{plan_name}}</strong> is scheduled for renewal on <strong>{{renewal_date}}</strong>.</p>
      </div>
    `,
    availableTokens: ["{{tenant_name}}", "{{plan_name}}", "{{renewal_date}}", "{{amount}}"],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
};

/**
 * Standardized, mandatory AVS Branded Footer
 * Injected into EVERY outgoing email sent via the platform.
 */
export function generateAvsBrandedFooter(config?: Partial<PlatformEmailSenderConfig>): string {
  const cfg = { ...DEFAULT_SENDER_CONFIG, ...config };
  return `
    <div style="margin-top: 32px; padding-top: 20px; border-top: 2px solid #f1f5f9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 11px; color: #64748b; line-height: 1.5;">
      <table width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td style="vertical-align: top; padding-bottom: 12px;">
            <div style="display: inline-block; font-weight: 800; font-size: 13px; color: #b45309; letter-spacing: 0.5px;">
              AVS GOLD ERP
            </div>
            <span style="font-size: 10px; color: #94a3b8; margin-left: 8px; font-family: monospace;">PLATFORM VERIFIED</span>
            <div style="margin-top: 4px; color: #475569; font-size: 11px;">
              Enterprise Jewellery Manufacturing, Bullion Accounting & Retail POS Solution
            </div>
          </td>
        </tr>
        <tr>
          <td style="background-color: #f8fafc; border-radius: 6px; padding: 12px; border: 1px solid #e2e8f0;">
            <div style="color: #334155; font-size: 11px;">
              <strong>Support & Governance:</strong> <a href="mailto:${cfg.supportEmail}" style="color: #b45309; text-decoration: none;">${cfg.supportEmail}</a>
              ${cfg.supportPhone ? ` &bull; <strong>Phone:</strong> ${cfg.supportPhone}` : ""}
              &bull; <strong>Web:</strong> <a href="${cfg.portalUrl}" style="color: #b45309; text-decoration: none;">${cfg.portalUrl}</a>
            </div>
            <div style="margin-top: 6px; font-size: 10px; color: #94a3b8;">
              ${cfg.legalDisclaimer}
            </div>
          </td>
        </tr>
      </table>
    </div>
  `;
}

/**
 * Load platform sender configuration from platform_settings table.
 */
export async function loadPlatformSenderConfig(): Promise<PlatformEmailSenderConfig> {
  // First check localStorage cache
  let localConfig: Partial<PlatformEmailSenderConfig> | null = null;
  try {
    const raw = localStorage.getItem("platform_email_sender_config");
    if (raw) localConfig = JSON.parse(raw);
  } catch {}

  try {
    const { data } = await supabase
      .from("platform_settings")
      .select("key, value")
      .in("key", [
        "email.from_email",
        "email.from_name",
        "email.reply_to",
        "email.smtp_host",
        "email.smtp_port",
        "email.support_phone",
        "email.support_email",
        "email.portal_url",
        "email.legal_disclaimer",
      ]);

    if (!data || data.length === 0) {
      return localConfig ? { ...DEFAULT_SENDER_CONFIG, ...localConfig } : DEFAULT_SENDER_CONFIG;
    }

    const map = new Map(data.map((r: { key: string; value: any }) => [r.key, r.value]));
    return {
      fromEmail: String(map.get("email.from_email") || localConfig?.fromEmail || DEFAULT_SENDER_CONFIG.fromEmail),
      fromName: String(map.get("email.from_name") || localConfig?.fromName || DEFAULT_SENDER_CONFIG.fromName),
      replyTo: String(map.get("email.reply_to") || localConfig?.replyTo || DEFAULT_SENDER_CONFIG.replyTo),
      smtpHost: String(map.get("email.smtp_host") || localConfig?.smtpHost || DEFAULT_SENDER_CONFIG.smtpHost),
      smtpPort: Number(map.get("email.smtp_port") || localConfig?.smtpPort || DEFAULT_SENDER_CONFIG.smtpPort),
      supportPhone: String(map.get("email.support_phone") || localConfig?.supportPhone || DEFAULT_SENDER_CONFIG.supportPhone),
      supportEmail: String(map.get("email.support_email") || localConfig?.supportEmail || DEFAULT_SENDER_CONFIG.supportEmail),
      portalUrl: String(map.get("email.portal_url") || localConfig?.portalUrl || DEFAULT_SENDER_CONFIG.portalUrl),
      legalDisclaimer: String(map.get("email.legal_disclaimer") || localConfig?.legalDisclaimer || DEFAULT_SENDER_CONFIG.legalDisclaimer),
    };
  } catch {
    return localConfig ? { ...DEFAULT_SENDER_CONFIG, ...localConfig } : DEFAULT_SENDER_CONFIG;
  }
}

/**
 * Save platform sender configuration
 */
export async function savePlatformSenderConfig(config: PlatformEmailSenderConfig): Promise<void> {
  // Always persist to local cache first
  try {
    localStorage.setItem("platform_email_sender_config", JSON.stringify(config));
  } catch {}

  const rows = [
    { key: "email.from_email", value: config.fromEmail },
    { key: "email.from_name", value: config.fromName },
    { key: "email.reply_to", value: config.replyTo },
    { key: "email.smtp_host", value: config.smtpHost },
    { key: "email.smtp_port", value: config.smtpPort },
    { key: "email.support_phone", value: config.supportPhone },
    { key: "email.support_email", value: config.supportEmail },
    { key: "email.portal_url", value: config.portalUrl },
    { key: "email.legal_disclaimer", value: config.legalDisclaimer },
  ];
  
  try {
    await supabase.from("platform_settings").upsert(rows);
  } catch {
    // Non-blocking if RLS restricts table writes; local cache is active
  }
}

/**
 * Load all central email templates
 */
export async function loadEmailTemplates(): Promise<EmailTemplateConfig[]> {
  try {
    const localRaw = localStorage.getItem("platform_email_templates");
    if (localRaw) {
      const parsed = JSON.parse(localRaw);
      if (typeof parsed === "object") {
        return Object.values(parsed) as unknown as EmailTemplateConfig[];
      }
    }
  } catch {}

  try {
    const { data } = await supabase
      .from("platform_settings")
      .select("value")
      .eq("key", "email.templates")
      .maybeSingle();

    if (data?.value && typeof data.value === "object") {
      return Object.values(data.value) as unknown as EmailTemplateConfig[];
    }
  } catch {
    // fallback
  }
  return Object.values(DEFAULT_EMAIL_TEMPLATES);
}

/**
 * Save email template
 */
export async function saveEmailTemplate(template: EmailTemplateConfig): Promise<void> {
  const all = await loadEmailTemplates();
  const map: Record<string, EmailTemplateConfig> = {};
  for (const t of all) map[t.templateCode] = t;
  map[template.templateCode] = { ...template, updatedAt: new Date().toISOString() };

  try {
    localStorage.setItem("platform_email_templates", JSON.stringify(map));
  } catch {}

  try {
    await supabase.from("platform_settings").upsert({
      key: "email.templates",
      value: map as any,
    });
  } catch {
    // Non-blocking if RLS restricts table writes; local cache is active
  }
}

/**
 * Render template with variables and inject mandatory AVS branded footer
 */
export function renderEmailBody(
  templateHtml: string,
  tokens: Record<string, string | number>,
  senderConfig?: Partial<PlatformEmailSenderConfig>,
): string {
  let rendered = templateHtml;
  for (const [key, val] of Object.entries(tokens)) {
    const pattern = new RegExp(key.replace(/[{}]/g, "\\$&"), "g");
    rendered = rendered.replace(pattern, String(val ?? ""));
  }
  const footer = generateAvsBrandedFooter(senderConfig);
  return `
    <div style="background-color: #ffffff; padding: 24px; max-width: 640px; margin: 0 auto; border-radius: 8px; border: 1px solid #e2e8f0;">
      ${rendered}
      ${footer}
    </div>
  `;
}

/**
 * Dispatch transactional email from the platform sender with automatic branding and audit logging
 */
export async function dispatchPlatformEmail(input: {
  to: string;
  subject: string;
  htmlBody: string;
  tenantId?: string;
  tenantName?: string;
  messageType?: string;
  documentRef?: string;
  attachments?: Array<{ filename: string; contentBase64: string; contentType?: string }>;
}): Promise<{ ok: boolean; error?: string }> {
  const senderCfg = await loadPlatformSenderConfig();
  
  // Ensure AVS Branded footer is attached if not already present
  const finalHtml = input.htmlBody.includes("AVS GOLD ERP")
    ? input.htmlBody
    : `${input.htmlBody}${generateAvsBrandedFooter(senderCfg)}`;

  try {
    const res = await fetch("/api/email/send.php", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        to: input.to,
        subject: input.subject,
        htmlBody: finalHtml,
        attachments: input.attachments || [],
        fromEmail: senderCfg.fromEmail,
        fromName: senderCfg.fromName,
        replyTo: senderCfg.replyTo,
      }),
    });

    const data = await res.json().catch(() => ({ success: res.ok }));
    const isSuccess = Boolean(res.ok && data?.success !== false);

    // Record in platform delivery audit log
    await supabase.from("platform_audit_events").insert({
      action: isSuccess ? "EMAIL_DISPATCHED" : "EMAIL_FAILED",
      target_type: "email",
      reason: `${input.messageType || "General"}: ${input.subject} -> ${input.to} (${isSuccess ? "Sent" : data?.error || "Failed"})`,
    });

    return { ok: isSuccess, error: isSuccess ? undefined : data?.error || `HTTP ${res.status}` };
  } catch (err: any) {
    await supabase.from("platform_audit_events").insert({
      action: "EMAIL_FAILED",
      target_type: "email",
      reason: `Exception sending to ${input.to}: ${err.message}`,
    });
    return { ok: false, error: err.message };
  }
}

export interface HostingerProviderConfig {
  provider: string;
  isConfigured: boolean;
  hasPassword: boolean;
  host: string;
  port: number;
  encryption: "SSL" | "TLS" | "SSL/TLS" | "STARTTLS";
  username: string;
  password?: string;
  fromEmail: string;
  fromName: string;
  replyTo: string;
  domain?: string;
  mxRecords?: string[];
  mxValid?: boolean;
  lastTestedAt?: string;
  lastTestStatus?: string;
}

export async function fetchHostingerProviderConfig(): Promise<HostingerProviderConfig> {
  try {
    const res = await fetch("/api/email/provider-config.php");
    if (res.ok) {
      const data = await res.json();
      return data;
    }
  } catch {}

  // Fallback defaults
  return {
    provider: "Hostinger Email",
    isConfigured: false,
    hasPassword: false,
    host: "smtp.hostinger.com",
    port: 465,
    encryption: "SSL/TLS",
    username: "",
    fromEmail: "notifications@arivahly.in",
    fromName: "AVS Gold ERP Platform",
    replyTo: "support@arivahly.in",
    domain: "arivahly.in",
  };
}

export async function saveHostingerProviderConfig(
  config: Partial<HostingerProviderConfig> & { autoTest?: boolean }
): Promise<{ success: boolean; config: HostingerProviderConfig; testResult?: any; error?: string }> {
  try {
    const res = await fetch("/api/email/provider-config.php", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(config),
    });
    const data = await res.json();
    return data;
  } catch (err: any) {
    return {
      success: false,
      config: config as any,
      error: err.message,
    };
  }
}

export async function testHostingerConnection(
  overrides?: Partial<HostingerProviderConfig>
): Promise<{
  success: boolean;
  status: string;
  host?: string;
  port?: number;
  encryption?: string;
  dnsResolved?: boolean;
  ipAddress?: string;
  tcpConnected?: boolean;
  tlsHandshake?: boolean;
  authenticated?: boolean;
  error?: string;
  diagnostics?: string[];
}> {
  try {
    const res = await fetch("/api/email/test-connection.php", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(overrides || {}),
    });
    const data = await res.json();
    return data;
  } catch (err: any) {
    return {
      success: false,
      status: "CONNECTION_FAILED",
      error: "Network error contacting SMTP test endpoint: " + err.message,
    };
  }
}

export async function sendHostingerTestEmail(
  to: string,
  overrides?: Partial<HostingerProviderConfig>
): Promise<{
  success: boolean;
  status: string;
  messageId?: string;
  provider?: string;
  smtpHost?: string;
  to?: string;
  from?: string;
  timestamp?: string;
  deliveryResult?: string;
  error?: string;
}> {
  try {
    const res = await fetch("/api/email/test-email.php", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ to, ...(overrides || {}) }),
    });
    const data = await res.json();
    return data;
  } catch (err: any) {
    return {
      success: false,
      status: "FAILED",
      error: "Network error sending test email: " + err.message,
    };
  }
}

export const getPlatformEmailConfig = loadPlatformSenderConfig;

export async function sendPlatformEmail(params: {
  tenantId?: string;
  templateKey?: string;
  recipientEmail: string;
  recipientName?: string;
  variables?: Record<string, string | number>;
  subject?: string;
  htmlBody?: string;
}): Promise<{ ok: boolean; error?: string }> {
  const templates = await loadEmailTemplates();
  const tmpl = templates.find((t) => t.templateCode === params.templateKey) || templates[0];
  const rendered = tmpl && params.variables
    ? renderEmailBody(tmpl.bodyHtml, params.variables)
    : params.htmlBody || "";
  const subj = tmpl && params.variables
    ? Object.entries(params.variables).reduce((acc, [k, v]) => acc.replace(new RegExp(k.replace(/[{}]/g, "\\$&"), "g"), String(v)), tmpl.subject)
    : params.subject || tmpl?.subject || "Notification from AVS Gold ERP";

  return dispatchPlatformEmail({
    to: params.recipientEmail,
    subject: subj,
    htmlBody: rendered,
    tenantId: params.tenantId,
    messageType: params.templateKey || "notification",
  });
}




