const jewelleryBookReportTemplate = builtin({
  id: "default_jewellery_book_report",
  docType: "fine_rojmel",
  name: "Jewellery Book Report (A4)",
  family: "dense_ledger",
  paperSize: "a4",
  sections: [
    { type: "header", id: "header", showQr: false },
    {
      type: "fieldGrid",
      id: "meta",
      columns: 2,
      fields: [
        { label: "Report", valuePath: "reportTitle", emphasis: true },
        { label: "Period", valuePath: "periodLabel" },
        { label: "Opening", valuePath: "openingLabel", showIf: "hasOpening" },
        { label: "Closing", valuePath: "closingLabel", showIf: "hasClosing" },
      ],
    },
    {
      type: "table",
      id: "lines",
      rowsPath: "lines",
      tableStyle: "classic",
      columns: [
        { key: "c1", header: "Col 1", align: "left", width: 1.1 },
        { key: "c2", header: "Col 2", align: "left", width: 1.1 },
        { key: "c3", header: "Col 3", align: "left", width: 2 },
        { key: "c4", header: "Col 4", align: "right", width: 0.9 },
        { key: "c5", header: "Col 5", align: "right", width: 0.9 },
        { key: "c6", header: "Col 6", align: "right", width: 0.9 },
      ],
    },
  ],
});

export const DEFAULT_TEMPLATES: Record<PrintDocType, PrintTemplate[]> = {
  gst_invoice: buildTemplatesForFamily("gst_invoice"),
  retail_invoice: buildTemplatesForFamily("retail_invoice"),
  estimate_doc: [estimateTemplate],
  invoice_quote_preview: [estimateTemplate],
  delivery_challan: [deliveryChallanTemplate],
  credit_note: [creditNoteTemplate],
  debit_note: [debitNoteTemplate],
  order_slip: [orderSlipTemplate],
  gold_receipt: [goldReceiptTemplate],
  advance_receipt: [advanceReceiptTemplate],
  old_gold_receipt: [goldReceiptTemplate],
  payment_receipt: [paymentReceiptTemplate],
  ratecut_slip: [ratecutSlipTemplate],
  jewellery_tag: [jewelleryTagTemplate],
  job_card: [jobCardTemplate],
  daily_material_slip: [dailyMaterialSlipTemplate],
  worker_material_given: [dailyMaterialSlipTemplate],
  worker_material_return: [dailyMaterialSlipTemplate],
  karigar_custody_statement: [karigarCustodyStatementTemplate],
  worker_passbook: [karigarCustodyStatementTemplate],
  filings_receipt: [dailyMaterialSlipTemplate],
  polishing_receipt: [dailyMaterialSlipTemplate],
  wastage_return_receipt: [dailyMaterialSlipTemplate],
  manufacturing_bill: [manufacturingBillTemplate],
  gold_settlement: [goldSettlementTemplate],
  settlement_draft: [goldSettlementTemplate],
};
