/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OtpLoginRouteImport } from './routes/otp-login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopIndexRouteImport } from './routes/workshop.index'
import { Route as StockIndexRouteImport } from './routes/stock.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as HardwareIndexRouteImport } from './routes/hardware/index'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as WorkshopWorkerBooksRouteImport } from './routes/workshop.worker-books'
import { Route as WorkshopGoldBookRouteImport } from './routes/workshop.gold-book'
import { Route as WorkshopIdRouteImport } from './routes/workshop.$id'
import { Route as StockVerificationRouteImport } from './routes/stock.verification'
import { Route as StockImportRouteImport } from './routes/stock.import'
import { Route as StockIdRouteImport } from './routes/stock.$id'
import { Route as SettingsWhatsappTemplatesRouteImport } from './routes/settings.whatsapp-templates'
import { Route as SettingsWhatsappRouteImport } from './routes/settings.whatsapp'
import { Route as SettingsStorageDiagnosticsRouteImport } from './routes/settings.storage-diagnostics'
import { Route as SettingsPrintTemplatesRouteImport } from './routes/settings.print-templates'
import { Route as SettingsCommunicationsRouteImport } from './routes/settings.communications'
import { Route as SettingsBranchSettingsRouteImport } from './routes/settings.branch-settings'
import { Route as SettingsAutomationRouteImport } from './routes/settings.automation'
import { Route as ReportsWorkerRouteImport } from './routes/reports.worker'
import { Route as ReportsVaultReconciliationRouteImport } from './routes/reports.vault-reconciliation'
import { Route as ReportsRemindersRouteImport } from './routes/reports.reminders'
import { Route as ReportsMonthEndCloseRouteImport } from './routes/reports.month-end-close'
import { Route as ReportsInventoryAgeingRouteImport } from './routes/reports.inventory-ageing'
import { Route as ReportsGoldSummaryRouteImport } from './routes/reports.gold-summary'
import { Route as ReportsGoldReconciliationRouteImport } from './routes/reports.gold-reconciliation'
import { Route as ReportsGoldPositionRouteImport } from './routes/reports.gold-position'
import { Route as ReportsGoldOutstandingRouteImport } from './routes/reports.gold-outstanding'
import { Route as ReportsExceptionsRouteImport } from './routes/reports.exceptions'
import { Route as ReportsDeliverySummaryRouteImport } from './routes/reports.delivery-summary'
import { Route as ReportsDailyGoldFlowRouteImport } from './routes/reports.daily-gold-flow'
import { Route as ReportsDailyCloseRouteImport } from './routes/reports.daily-close'
import { Route as ReportsCommunicationAnalyticsRouteImport } from './routes/reports.communication-analytics'
import { Route as ReportsAuditLogRouteImport } from './routes/reports.audit-log'
import { Route as ReportsApprovalsRouteImport } from './routes/reports.approvals'
import { Route as PeopleImportRouteImport } from './routes/people.import'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'
import { Route as DocTokenRouteImport } from './routes/doc.$token'
import { Route as BillingNewRouteImport } from './routes/billing.new'
import { Route as BillingIdRouteImport } from './routes/billing.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BillingEstimatesIndexRouteImport } from './routes/billing.estimates.index'
import { Route as BillingDeliveryChallansIndexRouteImport } from './routes/billing.delivery-challans.index'
import { Route as BillingDebitNotesIndexRouteImport } from './routes/billing.debit-notes.index'
import { Route as BillingCreditNotesIndexRouteImport } from './routes/billing.credit-notes.index'
import { Route as WorkshopWorkerBookWorkerIdRouteImport } from './routes/workshop.worker-book.$workerId'
import { Route as WorkshopReceiveSlipIdRouteImport } from './routes/workshop.receive-slip.$id'
import { Route as WorkshopGoldBookPrintWorkerIdRouteImport } from './routes/workshop.gold-book-print.$workerId'
import { Route as WorkshopFilingsSlipIdRouteImport } from './routes/workshop.filings-slip.$id'
import { Route as WorkshopBookJewellerIdRouteImport } from './routes/workshop.book.$jewellerId'
import { Route as StockPrintIdRouteImport } from './routes/stock.print.$id'
import { Route as ReportsDailyclosePrintIdRouteImport } from './routes/reports.dailyclose-print.$id'
import { Route as PeoplePrintIdRouteImport } from './routes/people.print.$id'
import { Route as PeopleLedgerPrintIdRouteImport } from './routes/people.ledger-print.$id'
import { Route as BillingReceiptIdRouteImport } from './routes/billing.receipt.$id'
import { Route as BillingPrintIdRouteImport } from './routes/billing.print.$id'
import { Route as BillingEstimatesIdRouteImport } from './routes/billing.estimates.$id'
import { Route as BillingEstimateIdRouteImport } from './routes/billing.estimate.$id'
import { Route as BillingEstimatePrintIdRouteImport } from './routes/billing.estimate-print.$id'
import { Route as BillingDeliveryChallansIdRouteImport } from './routes/billing.delivery-challans.$id'
import { Route as BillingDeliveryChallanPrintIdRouteImport } from './routes/billing.delivery-challan-print.$id'
import { Route as BillingDebitNotesIdRouteImport } from './routes/billing.debit-notes.$id'
import { Route as BillingDebitNotePrintIdRouteImport } from './routes/billing.debit-note-print.$id'
import { Route as BillingCreditNotesIdRouteImport } from './routes/billing.credit-notes.$id'
import { Route as BillingCreditNotePrintIdRouteImport } from './routes/billing.credit-note-print.$id'
import { Route as WorkshopMaterialSlipWorkerIdDateRouteImport } from './routes/workshop.material-slip.$workerId.$date'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpLoginRoute = OtpLoginRouteImport.update({
  id: '/otp-login',
  path: '/otp-login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopIndexRoute = WorkshopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkshopRoute,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareIndexRoute = HardwareIndexRouteImport.update({
  id: '/hardware/',
  path: '/hardware/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillingRoute,
} as any)
const WorkshopWorkerBooksRoute = WorkshopWorkerBooksRouteImport.update({
  id: '/worker-books',
  path: '/worker-books',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopGoldBookRoute = WorkshopGoldBookRouteImport.update({
  id: '/gold-book',
  path: '/gold-book',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopIdRoute = WorkshopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkshopRoute,
} as any)
const StockVerificationRoute = StockVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => StockRoute,
} as any)
const StockImportRoute = StockImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => StockRoute,
} as any)
const StockIdRoute = StockIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StockRoute,
} as any)
const SettingsWhatsappTemplatesRoute =
  SettingsWhatsappTemplatesRouteImport.update({
    id: '/whatsapp-templates',
    path: '/whatsapp-templates',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsWhatsappRoute = SettingsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStorageDiagnosticsRoute =
  SettingsStorageDiagnosticsRouteImport.update({
    id: '/storage-diagnostics',
    path: '/storage-diagnostics',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsPrintTemplatesRoute = SettingsPrintTemplatesRouteImport.update({
  id: '/print-templates',
  path: '/print-templates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCommunicationsRoute = SettingsCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBranchSettingsRoute = SettingsBranchSettingsRouteImport.update({
  id: '/branch-settings',
  path: '/branch-settings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutomationRoute = SettingsAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => SettingsRoute,
} as any)
const ReportsWorkerRoute = ReportsWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsVaultReconciliationRoute =
  ReportsVaultReconciliationRouteImport.update({
    id: '/vault-reconciliation',
    path: '/vault-reconciliation',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsRemindersRoute = ReportsRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsMonthEndCloseRoute = ReportsMonthEndCloseRouteImport.update({
  id: '/month-end-close',
  path: '/month-end-close',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsInventoryAgeingRoute = ReportsInventoryAgeingRouteImport.update({
  id: '/inventory-ageing',
  path: '/inventory-ageing',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsGoldSummaryRoute = ReportsGoldSummaryRouteImport.update({
  id: '/gold-summary',
  path: '/gold-summary',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsGoldReconciliationRoute =
  ReportsGoldReconciliationRouteImport.update({
    id: '/gold-reconciliation',
    path: '/gold-reconciliation',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsGoldPositionRoute = ReportsGoldPositionRouteImport.update({
  id: '/gold-position',
  path: '/gold-position',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsGoldOutstandingRoute = ReportsGoldOutstandingRouteImport.update({
  id: '/gold-outstanding',
  path: '/gold-outstanding',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsExceptionsRoute = ReportsExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDeliverySummaryRoute = ReportsDeliverySummaryRouteImport.update({
  id: '/delivery-summary',
  path: '/delivery-summary',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDailyGoldFlowRoute = ReportsDailyGoldFlowRouteImport.update({
  id: '/daily-gold-flow',
  path: '/daily-gold-flow',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDailyCloseRoute = ReportsDailyCloseRouteImport.update({
  id: '/daily-close',
  path: '/daily-close',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsCommunicationAnalyticsRoute =
  ReportsCommunicationAnalyticsRouteImport.update({
    id: '/communication-analytics',
    path: '/communication-analytics',
    getParentRoute: () => ReportsRoute,
  } as any)
const ReportsAuditLogRoute = ReportsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsApprovalsRoute = ReportsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ReportsRoute,
} as any)
const PeopleImportRoute = PeopleImportRouteImport.update({
  id: '/people/import',
  path: '/people/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => InviteRoute,
} as any)
const DocTokenRoute = DocTokenRouteImport.update({
  id: '/doc/$token',
  path: '/doc/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingNewRoute = BillingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BillingRoute,
} as any)
const BillingIdRoute = BillingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BillingRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingEstimatesIndexRoute = BillingEstimatesIndexRouteImport.update({
  id: '/estimates/',
  path: '/estimates/',
  getParentRoute: () => BillingRoute,
} as any)
const BillingDeliveryChallansIndexRoute =
  BillingDeliveryChallansIndexRouteImport.update({
    id: '/delivery-challans/',
    path: '/delivery-challans/',
    getParentRoute: () => BillingRoute,
  } as any)
const BillingDebitNotesIndexRoute = BillingDebitNotesIndexRouteImport.update({
  id: '/debit-notes/',
  path: '/debit-notes/',
  getParentRoute: () => BillingRoute,
} as any)
const BillingCreditNotesIndexRoute = BillingCreditNotesIndexRouteImport.update({
  id: '/credit-notes/',
  path: '/credit-notes/',
  getParentRoute: () => BillingRoute,
} as any)
const WorkshopWorkerBookWorkerIdRoute =
  WorkshopWorkerBookWorkerIdRouteImport.update({
    id: '/worker-book/$workerId',
    path: '/worker-book/$workerId',
    getParentRoute: () => WorkshopRoute,
  } as any)
const WorkshopReceiveSlipIdRoute = WorkshopReceiveSlipIdRouteImport.update({
  id: '/receive-slip/$id',
  path: '/receive-slip/$id',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopGoldBookPrintWorkerIdRoute =
  WorkshopGoldBookPrintWorkerIdRouteImport.update({
    id: '/gold-book-print/$workerId',
    path: '/gold-book-print/$workerId',
    getParentRoute: () => WorkshopRoute,
  } as any)
const WorkshopFilingsSlipIdRoute = WorkshopFilingsSlipIdRouteImport.update({
  id: '/filings-slip/$id',
  path: '/filings-slip/$id',
  getParentRoute: () => WorkshopRoute,
} as any)
const WorkshopBookJewellerIdRoute = WorkshopBookJewellerIdRouteImport.update({
  id: '/book/$jewellerId',
  path: '/book/$jewellerId',
  getParentRoute: () => WorkshopRoute,
} as any)
const StockPrintIdRoute = StockPrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => StockRoute,
} as any)
const ReportsDailyclosePrintIdRoute =
  ReportsDailyclosePrintIdRouteImport.update({
    id: '/dailyclose-print/$id',
    path: '/dailyclose-print/$id',
    getParentRoute: () => ReportsRoute,
  } as any)
const PeoplePrintIdRoute = PeoplePrintIdRouteImport.update({
  id: '/people/print/$id',
  path: '/people/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleLedgerPrintIdRoute = PeopleLedgerPrintIdRouteImport.update({
  id: '/people/ledger-print/$id',
  path: '/people/ledger-print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingReceiptIdRoute = BillingReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingPrintIdRoute = BillingPrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingEstimatesIdRoute = BillingEstimatesIdRouteImport.update({
  id: '/estimates/$id',
  path: '/estimates/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingEstimateIdRoute = BillingEstimateIdRouteImport.update({
  id: '/estimate/$id',
  path: '/estimate/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingEstimatePrintIdRoute = BillingEstimatePrintIdRouteImport.update({
  id: '/estimate-print/$id',
  path: '/estimate-print/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingDeliveryChallansIdRoute =
  BillingDeliveryChallansIdRouteImport.update({
    id: '/delivery-challans/$id',
    path: '/delivery-challans/$id',
    getParentRoute: () => BillingRoute,
  } as any)
const BillingDeliveryChallanPrintIdRoute =
  BillingDeliveryChallanPrintIdRouteImport.update({
    id: '/delivery-challan-print/$id',
    path: '/delivery-challan-print/$id',
    getParentRoute: () => BillingRoute,
  } as any)
const BillingDebitNotesIdRoute = BillingDebitNotesIdRouteImport.update({
  id: '/debit-notes/$id',
  path: '/debit-notes/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingDebitNotePrintIdRoute = BillingDebitNotePrintIdRouteImport.update({
  id: '/debit-note-print/$id',
  path: '/debit-note-print/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingCreditNotesIdRoute = BillingCreditNotesIdRouteImport.update({
  id: '/credit-notes/$id',
  path: '/credit-notes/$id',
  getParentRoute: () => BillingRoute,
} as any)
const BillingCreditNotePrintIdRoute =
  BillingCreditNotePrintIdRouteImport.update({
    id: '/credit-note-print/$id',
    path: '/credit-note-print/$id',
    getParentRoute: () => BillingRoute,
  } as any)
const WorkshopMaterialSlipWorkerIdDateRoute =
  WorkshopMaterialSlipWorkerIdDateRouteImport.update({
    id: '/material-slip/$workerId/$date',
    path: '/material-slip/$workerId/$date',
    getParentRoute: () => WorkshopRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/invite': typeof InviteRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
  '/otp-login': typeof OtpLoginRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/stock': typeof StockRouteWithChildren
  '/verify': typeof VerifyRoute
  '/whatsapp': typeof WhatsappRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/$id': typeof BillingIdRoute
  '/billing/new': typeof BillingNewRoute
  '/doc/$token': typeof DocTokenRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/import': typeof PeopleImportRoute
  '/reports/approvals': typeof ReportsApprovalsRoute
  '/reports/audit-log': typeof ReportsAuditLogRoute
  '/reports/communication-analytics': typeof ReportsCommunicationAnalyticsRoute
  '/reports/daily-close': typeof ReportsDailyCloseRoute
  '/reports/daily-gold-flow': typeof ReportsDailyGoldFlowRoute
  '/reports/delivery-summary': typeof ReportsDeliverySummaryRoute
  '/reports/exceptions': typeof ReportsExceptionsRoute
  '/reports/gold-outstanding': typeof ReportsGoldOutstandingRoute
  '/reports/gold-position': typeof ReportsGoldPositionRoute
  '/reports/gold-reconciliation': typeof ReportsGoldReconciliationRoute
  '/reports/gold-summary': typeof ReportsGoldSummaryRoute
  '/reports/inventory-ageing': typeof ReportsInventoryAgeingRoute
  '/reports/month-end-close': typeof ReportsMonthEndCloseRoute
  '/reports/reminders': typeof ReportsRemindersRoute
  '/reports/vault-reconciliation': typeof ReportsVaultReconciliationRoute
  '/reports/worker': typeof ReportsWorkerRoute
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/branch-settings': typeof SettingsBranchSettingsRoute
  '/settings/communications': typeof SettingsCommunicationsRoute
  '/settings/print-templates': typeof SettingsPrintTemplatesRoute
  '/settings/storage-diagnostics': typeof SettingsStorageDiagnosticsRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/whatsapp-templates': typeof SettingsWhatsappTemplatesRoute
  '/stock/$id': typeof StockIdRoute
  '/stock/import': typeof StockImportRoute
  '/stock/verification': typeof StockVerificationRoute
  '/workshop/$id': typeof WorkshopIdRoute
  '/workshop/gold-book': typeof WorkshopGoldBookRoute
  '/workshop/worker-books': typeof WorkshopWorkerBooksRoute
  '/billing/': typeof BillingIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/hardware/': typeof HardwareIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stock/': typeof StockIndexRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/billing/credit-note-print/$id': typeof BillingCreditNotePrintIdRoute
  '/billing/credit-notes/$id': typeof BillingCreditNotesIdRoute
  '/billing/debit-note-print/$id': typeof BillingDebitNotePrintIdRoute
  '/billing/debit-notes/$id': typeof BillingDebitNotesIdRoute
  '/billing/delivery-challan-print/$id': typeof BillingDeliveryChallanPrintIdRoute
  '/billing/delivery-challans/$id': typeof BillingDeliveryChallansIdRoute
  '/billing/estimate-print/$id': typeof BillingEstimatePrintIdRoute
  '/billing/estimate/$id': typeof BillingEstimateIdRoute
  '/billing/estimates/$id': typeof BillingEstimatesIdRoute
  '/billing/print/$id': typeof BillingPrintIdRoute
  '/billing/receipt/$id': typeof BillingReceiptIdRoute
  '/people/ledger-print/$id': typeof PeopleLedgerPrintIdRoute
  '/people/print/$id': typeof PeoplePrintIdRoute
  '/reports/dailyclose-print/$id': typeof ReportsDailyclosePrintIdRoute
  '/stock/print/$id': typeof StockPrintIdRoute
  '/workshop/book/$jewellerId': typeof WorkshopBookJewellerIdRoute
  '/workshop/filings-slip/$id': typeof WorkshopFilingsSlipIdRoute
  '/workshop/gold-book-print/$workerId': typeof WorkshopGoldBookPrintWorkerIdRoute
  '/workshop/receive-slip/$id': typeof WorkshopReceiveSlipIdRoute
  '/workshop/worker-book/$workerId': typeof WorkshopWorkerBookWorkerIdRoute
  '/billing/credit-notes/': typeof BillingCreditNotesIndexRoute
  '/billing/debit-notes/': typeof BillingDebitNotesIndexRoute
  '/billing/delivery-challans/': typeof BillingDeliveryChallansIndexRoute
  '/billing/estimates/': typeof BillingEstimatesIndexRoute
  '/workshop/material-slip/$workerId/$date': typeof WorkshopMaterialSlipWorkerIdDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/invite': typeof InviteRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
  '/otp-login': typeof OtpLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify': typeof VerifyRoute
  '/whatsapp': typeof WhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/$id': typeof BillingIdRoute
  '/billing/new': typeof BillingNewRoute
  '/doc/$token': typeof DocTokenRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/import': typeof PeopleImportRoute
  '/reports/approvals': typeof ReportsApprovalsRoute
  '/reports/audit-log': typeof ReportsAuditLogRoute
  '/reports/communication-analytics': typeof ReportsCommunicationAnalyticsRoute
  '/reports/daily-close': typeof ReportsDailyCloseRoute
  '/reports/daily-gold-flow': typeof ReportsDailyGoldFlowRoute
  '/reports/delivery-summary': typeof ReportsDeliverySummaryRoute
  '/reports/exceptions': typeof ReportsExceptionsRoute
  '/reports/gold-outstanding': typeof ReportsGoldOutstandingRoute
  '/reports/gold-position': typeof ReportsGoldPositionRoute
  '/reports/gold-reconciliation': typeof ReportsGoldReconciliationRoute
  '/reports/gold-summary': typeof ReportsGoldSummaryRoute
  '/reports/inventory-ageing': typeof ReportsInventoryAgeingRoute
  '/reports/month-end-close': typeof ReportsMonthEndCloseRoute
  '/reports/reminders': typeof ReportsRemindersRoute
  '/reports/vault-reconciliation': typeof ReportsVaultReconciliationRoute
  '/reports/worker': typeof ReportsWorkerRoute
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/branch-settings': typeof SettingsBranchSettingsRoute
  '/settings/communications': typeof SettingsCommunicationsRoute
  '/settings/print-templates': typeof SettingsPrintTemplatesRoute
  '/settings/storage-diagnostics': typeof SettingsStorageDiagnosticsRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/whatsapp-templates': typeof SettingsWhatsappTemplatesRoute
  '/stock/$id': typeof StockIdRoute
  '/stock/import': typeof StockImportRoute
  '/stock/verification': typeof StockVerificationRoute
  '/workshop/$id': typeof WorkshopIdRoute
  '/workshop/gold-book': typeof WorkshopGoldBookRoute
  '/workshop/worker-books': typeof WorkshopWorkerBooksRoute
  '/billing': typeof BillingIndexRoute
  '/branches': typeof BranchesIndexRoute
  '/hardware': typeof HardwareIndexRoute
  '/people': typeof PeopleIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stock': typeof StockIndexRoute
  '/workshop': typeof WorkshopIndexRoute
  '/billing/credit-note-print/$id': typeof BillingCreditNotePrintIdRoute
  '/billing/credit-notes/$id': typeof BillingCreditNotesIdRoute
  '/billing/debit-note-print/$id': typeof BillingDebitNotePrintIdRoute
  '/billing/debit-notes/$id': typeof BillingDebitNotesIdRoute
  '/billing/delivery-challan-print/$id': typeof BillingDeliveryChallanPrintIdRoute
  '/billing/delivery-challans/$id': typeof BillingDeliveryChallansIdRoute
  '/billing/estimate-print/$id': typeof BillingEstimatePrintIdRoute
  '/billing/estimate/$id': typeof BillingEstimateIdRoute
  '/billing/estimates/$id': typeof BillingEstimatesIdRoute
  '/billing/print/$id': typeof BillingPrintIdRoute
  '/billing/receipt/$id': typeof BillingReceiptIdRoute
  '/people/ledger-print/$id': typeof PeopleLedgerPrintIdRoute
  '/people/print/$id': typeof PeoplePrintIdRoute
  '/reports/dailyclose-print/$id': typeof ReportsDailyclosePrintIdRoute
  '/stock/print/$id': typeof StockPrintIdRoute
  '/workshop/book/$jewellerId': typeof WorkshopBookJewellerIdRoute
  '/workshop/filings-slip/$id': typeof WorkshopFilingsSlipIdRoute
  '/workshop/gold-book-print/$workerId': typeof WorkshopGoldBookPrintWorkerIdRoute
  '/workshop/receive-slip/$id': typeof WorkshopReceiveSlipIdRoute
  '/workshop/worker-book/$workerId': typeof WorkshopWorkerBookWorkerIdRoute
  '/billing/credit-notes': typeof BillingCreditNotesIndexRoute
  '/billing/debit-notes': typeof BillingDebitNotesIndexRoute
  '/billing/delivery-challans': typeof BillingDeliveryChallansIndexRoute
  '/billing/estimates': typeof BillingEstimatesIndexRoute
  '/workshop/material-slip/$workerId/$date': typeof WorkshopMaterialSlipWorkerIdDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/invite': typeof InviteRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
  '/otp-login': typeof OtpLoginRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/stock': typeof StockRouteWithChildren
  '/verify': typeof VerifyRoute
  '/whatsapp': typeof WhatsappRoute
  '/workshop': typeof WorkshopRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/$id': typeof BillingIdRoute
  '/billing/new': typeof BillingNewRoute
  '/doc/$token': typeof DocTokenRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/import': typeof PeopleImportRoute
  '/reports/approvals': typeof ReportsApprovalsRoute
  '/reports/audit-log': typeof ReportsAuditLogRoute
  '/reports/communication-analytics': typeof ReportsCommunicationAnalyticsRoute
  '/reports/daily-close': typeof ReportsDailyCloseRoute
  '/reports/daily-gold-flow': typeof ReportsDailyGoldFlowRoute
  '/reports/delivery-summary': typeof ReportsDeliverySummaryRoute
  '/reports/exceptions': typeof ReportsExceptionsRoute
  '/reports/gold-outstanding': typeof ReportsGoldOutstandingRoute
  '/reports/gold-position': typeof ReportsGoldPositionRoute
  '/reports/gold-reconciliation': typeof ReportsGoldReconciliationRoute
  '/reports/gold-summary': typeof ReportsGoldSummaryRoute
  '/reports/inventory-ageing': typeof ReportsInventoryAgeingRoute
  '/reports/month-end-close': typeof ReportsMonthEndCloseRoute
  '/reports/reminders': typeof ReportsRemindersRoute
  '/reports/vault-reconciliation': typeof ReportsVaultReconciliationRoute
  '/reports/worker': typeof ReportsWorkerRoute
  '/settings/automation': typeof SettingsAutomationRoute
  '/settings/branch-settings': typeof SettingsBranchSettingsRoute
  '/settings/communications': typeof SettingsCommunicationsRoute
  '/settings/print-templates': typeof SettingsPrintTemplatesRoute
  '/settings/storage-diagnostics': typeof SettingsStorageDiagnosticsRoute
  '/settings/whatsapp': typeof SettingsWhatsappRoute
  '/settings/whatsapp-templates': typeof SettingsWhatsappTemplatesRoute
  '/stock/$id': typeof StockIdRoute
  '/stock/import': typeof StockImportRoute
  '/stock/verification': typeof StockVerificationRoute
  '/workshop/$id': typeof WorkshopIdRoute
  '/workshop/gold-book': typeof WorkshopGoldBookRoute
  '/workshop/worker-books': typeof WorkshopWorkerBooksRoute
  '/billing/': typeof BillingIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/hardware/': typeof HardwareIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stock/': typeof StockIndexRoute
  '/workshop/': typeof WorkshopIndexRoute
  '/billing/credit-note-print/$id': typeof BillingCreditNotePrintIdRoute
  '/billing/credit-notes/$id': typeof BillingCreditNotesIdRoute
  '/billing/debit-note-print/$id': typeof BillingDebitNotePrintIdRoute
  '/billing/debit-notes/$id': typeof BillingDebitNotesIdRoute
  '/billing/delivery-challan-print/$id': typeof BillingDeliveryChallanPrintIdRoute
  '/billing/delivery-challans/$id': typeof BillingDeliveryChallansIdRoute
  '/billing/estimate-print/$id': typeof BillingEstimatePrintIdRoute
  '/billing/estimate/$id': typeof BillingEstimateIdRoute
  '/billing/estimates/$id': typeof BillingEstimatesIdRoute
  '/billing/print/$id': typeof BillingPrintIdRoute
  '/billing/receipt/$id': typeof BillingReceiptIdRoute
  '/people/ledger-print/$id': typeof PeopleLedgerPrintIdRoute
  '/people/print/$id': typeof PeoplePrintIdRoute
  '/reports/dailyclose-print/$id': typeof ReportsDailyclosePrintIdRoute
  '/stock/print/$id': typeof StockPrintIdRoute
  '/workshop/book/$jewellerId': typeof WorkshopBookJewellerIdRoute
  '/workshop/filings-slip/$id': typeof WorkshopFilingsSlipIdRoute
  '/workshop/gold-book-print/$workerId': typeof WorkshopGoldBookPrintWorkerIdRoute
  '/workshop/receive-slip/$id': typeof WorkshopReceiveSlipIdRoute
  '/workshop/worker-book/$workerId': typeof WorkshopWorkerBookWorkerIdRoute
  '/billing/credit-notes/': typeof BillingCreditNotesIndexRoute
  '/billing/debit-notes/': typeof BillingDebitNotesIndexRoute
  '/billing/delivery-challans/': typeof BillingDeliveryChallansIndexRoute
  '/billing/estimates/': typeof BillingEstimatesIndexRoute
  '/workshop/material-slip/$workerId/$date': typeof WorkshopMaterialSlipWorkerIdDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/documents'
    | '/forgot-password'
    | '/help'
    | '/invite'
    | '/ledger'
    | '/notifications'
    | '/otp-login'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/stock'
    | '/verify'
    | '/whatsapp'
    | '/workshop'
    | '/auth/callback'
    | '/billing/$id'
    | '/billing/new'
    | '/doc/$token'
    | '/invite/accept'
    | '/people/$id'
    | '/people/import'
    | '/reports/approvals'
    | '/reports/audit-log'
    | '/reports/communication-analytics'
    | '/reports/daily-close'
    | '/reports/daily-gold-flow'
    | '/reports/delivery-summary'
    | '/reports/exceptions'
    | '/reports/gold-outstanding'
    | '/reports/gold-position'
    | '/reports/gold-reconciliation'
    | '/reports/gold-summary'
    | '/reports/inventory-ageing'
    | '/reports/month-end-close'
    | '/reports/reminders'
    | '/reports/vault-reconciliation'
    | '/reports/worker'
    | '/settings/automation'
    | '/settings/branch-settings'
    | '/settings/communications'
    | '/settings/print-templates'
    | '/settings/storage-diagnostics'
    | '/settings/whatsapp'
    | '/settings/whatsapp-templates'
    | '/stock/$id'
    | '/stock/import'
    | '/stock/verification'
    | '/workshop/$id'
    | '/workshop/gold-book'
    | '/workshop/worker-books'
    | '/billing/'
    | '/branches/'
    | '/hardware/'
    | '/people/'
    | '/reports/'
    | '/settings/'
    | '/stock/'
    | '/workshop/'
    | '/billing/credit-note-print/$id'
    | '/billing/credit-notes/$id'
    | '/billing/debit-note-print/$id'
    | '/billing/debit-notes/$id'
    | '/billing/delivery-challan-print/$id'
    | '/billing/delivery-challans/$id'
    | '/billing/estimate-print/$id'
    | '/billing/estimate/$id'
    | '/billing/estimates/$id'
    | '/billing/print/$id'
    | '/billing/receipt/$id'
    | '/people/ledger-print/$id'
    | '/people/print/$id'
    | '/reports/dailyclose-print/$id'
    | '/stock/print/$id'
    | '/workshop/book/$jewellerId'
    | '/workshop/filings-slip/$id'
    | '/workshop/gold-book-print/$workerId'
    | '/workshop/receive-slip/$id'
    | '/workshop/worker-book/$workerId'
    | '/billing/credit-notes/'
    | '/billing/debit-notes/'
    | '/billing/delivery-challans/'
    | '/billing/estimates/'
    | '/workshop/material-slip/$workerId/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/forgot-password'
    | '/help'
    | '/invite'
    | '/ledger'
    | '/notifications'
    | '/otp-login'
    | '/reset-password'
    | '/setup'
    | '/verify'
    | '/whatsapp'
    | '/auth/callback'
    | '/billing/$id'
    | '/billing/new'
    | '/doc/$token'
    | '/invite/accept'
    | '/people/$id'
    | '/people/import'
    | '/reports/approvals'
    | '/reports/audit-log'
    | '/reports/communication-analytics'
    | '/reports/daily-close'
    | '/reports/daily-gold-flow'
    | '/reports/delivery-summary'
    | '/reports/exceptions'
    | '/reports/gold-outstanding'
    | '/reports/gold-position'
    | '/reports/gold-reconciliation'
    | '/reports/gold-summary'
    | '/reports/inventory-ageing'
    | '/reports/month-end-close'
    | '/reports/reminders'
    | '/reports/vault-reconciliation'
    | '/reports/worker'
    | '/settings/automation'
    | '/settings/branch-settings'
    | '/settings/communications'
    | '/settings/print-templates'
    | '/settings/storage-diagnostics'
    | '/settings/whatsapp'
    | '/settings/whatsapp-templates'
    | '/stock/$id'
    | '/stock/import'
    | '/stock/verification'
    | '/workshop/$id'
    | '/workshop/gold-book'
    | '/workshop/worker-books'
    | '/billing'
    | '/branches'
    | '/hardware'
    | '/people'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/workshop'
    | '/billing/credit-note-print/$id'
    | '/billing/credit-notes/$id'
    | '/billing/debit-note-print/$id'
    | '/billing/debit-notes/$id'
    | '/billing/delivery-challan-print/$id'
    | '/billing/delivery-challans/$id'
    | '/billing/estimate-print/$id'
    | '/billing/estimate/$id'
    | '/billing/estimates/$id'
    | '/billing/print/$id'
    | '/billing/receipt/$id'
    | '/people/ledger-print/$id'
    | '/people/print/$id'
    | '/reports/dailyclose-print/$id'
    | '/stock/print/$id'
    | '/workshop/book/$jewellerId'
    | '/workshop/filings-slip/$id'
    | '/workshop/gold-book-print/$workerId'
    | '/workshop/receive-slip/$id'
    | '/workshop/worker-book/$workerId'
    | '/billing/credit-notes'
    | '/billing/debit-notes'
    | '/billing/delivery-challans'
    | '/billing/estimates'
    | '/workshop/material-slip/$workerId/$date'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/documents'
    | '/forgot-password'
    | '/help'
    | '/invite'
    | '/ledger'
    | '/notifications'
    | '/otp-login'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/stock'
    | '/verify'
    | '/whatsapp'
    | '/workshop'
    | '/auth/callback'
    | '/billing/$id'
    | '/billing/new'
    | '/doc/$token'
    | '/invite/accept'
    | '/people/$id'
    | '/people/import'
    | '/reports/approvals'
    | '/reports/audit-log'
    | '/reports/communication-analytics'
    | '/reports/daily-close'
    | '/reports/daily-gold-flow'
    | '/reports/delivery-summary'
    | '/reports/exceptions'
    | '/reports/gold-outstanding'
    | '/reports/gold-position'
    | '/reports/gold-reconciliation'
    | '/reports/gold-summary'
    | '/reports/inventory-ageing'
    | '/reports/month-end-close'
    | '/reports/reminders'
    | '/reports/vault-reconciliation'
    | '/reports/worker'
    | '/settings/automation'
    | '/settings/branch-settings'
    | '/settings/communications'
    | '/settings/print-templates'
    | '/settings/storage-diagnostics'
    | '/settings/whatsapp'
    | '/settings/whatsapp-templates'
    | '/stock/$id'
    | '/stock/import'
    | '/stock/verification'
    | '/workshop/$id'
    | '/workshop/gold-book'
    | '/workshop/worker-books'
    | '/billing/'
    | '/branches/'
    | '/hardware/'
    | '/people/'
    | '/reports/'
    | '/settings/'
    | '/stock/'
    | '/workshop/'
    | '/billing/credit-note-print/$id'
    | '/billing/credit-notes/$id'
    | '/billing/debit-note-print/$id'
    | '/billing/debit-notes/$id'
    | '/billing/delivery-challan-print/$id'
    | '/billing/delivery-challans/$id'
    | '/billing/estimate-print/$id'
    | '/billing/estimate/$id'
    | '/billing/estimates/$id'
    | '/billing/print/$id'
    | '/billing/receipt/$id'
    | '/people/ledger-print/$id'
    | '/people/print/$id'
    | '/reports/dailyclose-print/$id'
    | '/stock/print/$id'
    | '/workshop/book/$jewellerId'
    | '/workshop/filings-slip/$id'
    | '/workshop/gold-book-print/$workerId'
    | '/workshop/receive-slip/$id'
    | '/workshop/worker-book/$workerId'
    | '/billing/credit-notes/'
    | '/billing/debit-notes/'
    | '/billing/delivery-challans/'
    | '/billing/estimates/'
    | '/workshop/material-slip/$workerId/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  InviteRoute: typeof InviteRouteWithChildren
  LedgerRoute: typeof LedgerRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpLoginRoute: typeof OtpLoginRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  StockRoute: typeof StockRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  WhatsappRoute: typeof WhatsappRoute
  WorkshopRoute: typeof WorkshopRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  DocTokenRoute: typeof DocTokenRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PeopleImportRoute: typeof PeopleImportRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  HardwareIndexRoute: typeof HardwareIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PeopleLedgerPrintIdRoute: typeof PeopleLedgerPrintIdRoute
  PeoplePrintIdRoute: typeof PeoplePrintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-login': {
      id: '/otp-login'
      path: '/otp-login'
      fullPath: '/otp-login'
      preLoaderRoute: typeof OtpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/': {
      id: '/workshop/'
      path: '/'
      fullPath: '/workshop/'
      preLoaderRoute: typeof WorkshopIndexRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/stock/': {
      id: '/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof StockRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware/': {
      id: '/hardware/'
      path: '/hardware'
      fullPath: '/hardware/'
      preLoaderRoute: typeof HardwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/workshop/worker-books': {
      id: '/workshop/worker-books'
      path: '/worker-books'
      fullPath: '/workshop/worker-books'
      preLoaderRoute: typeof WorkshopWorkerBooksRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/gold-book': {
      id: '/workshop/gold-book'
      path: '/gold-book'
      fullPath: '/workshop/gold-book'
      preLoaderRoute: typeof WorkshopGoldBookRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/$id': {
      id: '/workshop/$id'
      path: '/$id'
      fullPath: '/workshop/$id'
      preLoaderRoute: typeof WorkshopIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/stock/verification': {
      id: '/stock/verification'
      path: '/verification'
      fullPath: '/stock/verification'
      preLoaderRoute: typeof StockVerificationRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/import': {
      id: '/stock/import'
      path: '/import'
      fullPath: '/stock/import'
      preLoaderRoute: typeof StockImportRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/$id': {
      id: '/stock/$id'
      path: '/$id'
      fullPath: '/stock/$id'
      preLoaderRoute: typeof StockIdRouteImport
      parentRoute: typeof StockRoute
    }
    '/settings/whatsapp-templates': {
      id: '/settings/whatsapp-templates'
      path: '/whatsapp-templates'
      fullPath: '/settings/whatsapp-templates'
      preLoaderRoute: typeof SettingsWhatsappTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/whatsapp': {
      id: '/settings/whatsapp'
      path: '/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof SettingsWhatsappRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/storage-diagnostics': {
      id: '/settings/storage-diagnostics'
      path: '/storage-diagnostics'
      fullPath: '/settings/storage-diagnostics'
      preLoaderRoute: typeof SettingsStorageDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/print-templates': {
      id: '/settings/print-templates'
      path: '/print-templates'
      fullPath: '/settings/print-templates'
      preLoaderRoute: typeof SettingsPrintTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/communications': {
      id: '/settings/communications'
      path: '/communications'
      fullPath: '/settings/communications'
      preLoaderRoute: typeof SettingsCommunicationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/branch-settings': {
      id: '/settings/branch-settings'
      path: '/branch-settings'
      fullPath: '/settings/branch-settings'
      preLoaderRoute: typeof SettingsBranchSettingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/automation': {
      id: '/settings/automation'
      path: '/automation'
      fullPath: '/settings/automation'
      preLoaderRoute: typeof SettingsAutomationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reports/worker': {
      id: '/reports/worker'
      path: '/worker'
      fullPath: '/reports/worker'
      preLoaderRoute: typeof ReportsWorkerRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/vault-reconciliation': {
      id: '/reports/vault-reconciliation'
      path: '/vault-reconciliation'
      fullPath: '/reports/vault-reconciliation'
      preLoaderRoute: typeof ReportsVaultReconciliationRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/reminders': {
      id: '/reports/reminders'
      path: '/reminders'
      fullPath: '/reports/reminders'
      preLoaderRoute: typeof ReportsRemindersRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/month-end-close': {
      id: '/reports/month-end-close'
      path: '/month-end-close'
      fullPath: '/reports/month-end-close'
      preLoaderRoute: typeof ReportsMonthEndCloseRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/inventory-ageing': {
      id: '/reports/inventory-ageing'
      path: '/inventory-ageing'
      fullPath: '/reports/inventory-ageing'
      preLoaderRoute: typeof ReportsInventoryAgeingRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/gold-summary': {
      id: '/reports/gold-summary'
      path: '/gold-summary'
      fullPath: '/reports/gold-summary'
      preLoaderRoute: typeof ReportsGoldSummaryRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/gold-reconciliation': {
      id: '/reports/gold-reconciliation'
      path: '/gold-reconciliation'
      fullPath: '/reports/gold-reconciliation'
      preLoaderRoute: typeof ReportsGoldReconciliationRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/gold-position': {
      id: '/reports/gold-position'
      path: '/gold-position'
      fullPath: '/reports/gold-position'
      preLoaderRoute: typeof ReportsGoldPositionRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/gold-outstanding': {
      id: '/reports/gold-outstanding'
      path: '/gold-outstanding'
      fullPath: '/reports/gold-outstanding'
      preLoaderRoute: typeof ReportsGoldOutstandingRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/exceptions': {
      id: '/reports/exceptions'
      path: '/exceptions'
      fullPath: '/reports/exceptions'
      preLoaderRoute: typeof ReportsExceptionsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/delivery-summary': {
      id: '/reports/delivery-summary'
      path: '/delivery-summary'
      fullPath: '/reports/delivery-summary'
      preLoaderRoute: typeof ReportsDeliverySummaryRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/daily-gold-flow': {
      id: '/reports/daily-gold-flow'
      path: '/daily-gold-flow'
      fullPath: '/reports/daily-gold-flow'
      preLoaderRoute: typeof ReportsDailyGoldFlowRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/daily-close': {
      id: '/reports/daily-close'
      path: '/daily-close'
      fullPath: '/reports/daily-close'
      preLoaderRoute: typeof ReportsDailyCloseRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/communication-analytics': {
      id: '/reports/communication-analytics'
      path: '/communication-analytics'
      fullPath: '/reports/communication-analytics'
      preLoaderRoute: typeof ReportsCommunicationAnalyticsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/audit-log': {
      id: '/reports/audit-log'
      path: '/audit-log'
      fullPath: '/reports/audit-log'
      preLoaderRoute: typeof ReportsAuditLogRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/approvals': {
      id: '/reports/approvals'
      path: '/approvals'
      fullPath: '/reports/approvals'
      preLoaderRoute: typeof ReportsApprovalsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/people/import': {
      id: '/people/import'
      path: '/people/import'
      fullPath: '/people/import'
      preLoaderRoute: typeof PeopleImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof InviteRoute
    }
    '/doc/$token': {
      id: '/doc/$token'
      path: '/doc/$token'
      fullPath: '/doc/$token'
      preLoaderRoute: typeof DocTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/new': {
      id: '/billing/new'
      path: '/new'
      fullPath: '/billing/new'
      preLoaderRoute: typeof BillingNewRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/$id': {
      id: '/billing/$id'
      path: '/$id'
      fullPath: '/billing/$id'
      preLoaderRoute: typeof BillingIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/estimates/': {
      id: '/billing/estimates/'
      path: '/estimates'
      fullPath: '/billing/estimates/'
      preLoaderRoute: typeof BillingEstimatesIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/delivery-challans/': {
      id: '/billing/delivery-challans/'
      path: '/delivery-challans'
      fullPath: '/billing/delivery-challans/'
      preLoaderRoute: typeof BillingDeliveryChallansIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/debit-notes/': {
      id: '/billing/debit-notes/'
      path: '/debit-notes'
      fullPath: '/billing/debit-notes/'
      preLoaderRoute: typeof BillingDebitNotesIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/credit-notes/': {
      id: '/billing/credit-notes/'
      path: '/credit-notes'
      fullPath: '/billing/credit-notes/'
      preLoaderRoute: typeof BillingCreditNotesIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/workshop/worker-book/$workerId': {
      id: '/workshop/worker-book/$workerId'
      path: '/worker-book/$workerId'
      fullPath: '/workshop/worker-book/$workerId'
      preLoaderRoute: typeof WorkshopWorkerBookWorkerIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/receive-slip/$id': {
      id: '/workshop/receive-slip/$id'
      path: '/receive-slip/$id'
      fullPath: '/workshop/receive-slip/$id'
      preLoaderRoute: typeof WorkshopReceiveSlipIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/gold-book-print/$workerId': {
      id: '/workshop/gold-book-print/$workerId'
      path: '/gold-book-print/$workerId'
      fullPath: '/workshop/gold-book-print/$workerId'
      preLoaderRoute: typeof WorkshopGoldBookPrintWorkerIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/filings-slip/$id': {
      id: '/workshop/filings-slip/$id'
      path: '/filings-slip/$id'
      fullPath: '/workshop/filings-slip/$id'
      preLoaderRoute: typeof WorkshopFilingsSlipIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/workshop/book/$jewellerId': {
      id: '/workshop/book/$jewellerId'
      path: '/book/$jewellerId'
      fullPath: '/workshop/book/$jewellerId'
      preLoaderRoute: typeof WorkshopBookJewellerIdRouteImport
      parentRoute: typeof WorkshopRoute
    }
    '/stock/print/$id': {
      id: '/stock/print/$id'
      path: '/print/$id'
      fullPath: '/stock/print/$id'
      preLoaderRoute: typeof StockPrintIdRouteImport
      parentRoute: typeof StockRoute
    }
    '/reports/dailyclose-print/$id': {
      id: '/reports/dailyclose-print/$id'
      path: '/dailyclose-print/$id'
      fullPath: '/reports/dailyclose-print/$id'
      preLoaderRoute: typeof ReportsDailyclosePrintIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/people/print/$id': {
      id: '/people/print/$id'
      path: '/people/print/$id'
      fullPath: '/people/print/$id'
      preLoaderRoute: typeof PeoplePrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/ledger-print/$id': {
      id: '/people/ledger-print/$id'
      path: '/people/ledger-print/$id'
      fullPath: '/people/ledger-print/$id'
      preLoaderRoute: typeof PeopleLedgerPrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/receipt/$id': {
      id: '/billing/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/billing/receipt/$id'
      preLoaderRoute: typeof BillingReceiptIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/print/$id': {
      id: '/billing/print/$id'
      path: '/print/$id'
      fullPath: '/billing/print/$id'
      preLoaderRoute: typeof BillingPrintIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/estimates/$id': {
      id: '/billing/estimates/$id'
      path: '/estimates/$id'
      fullPath: '/billing/estimates/$id'
      preLoaderRoute: typeof BillingEstimatesIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/estimate/$id': {
      id: '/billing/estimate/$id'
      path: '/estimate/$id'
      fullPath: '/billing/estimate/$id'
      preLoaderRoute: typeof BillingEstimateIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/estimate-print/$id': {
      id: '/billing/estimate-print/$id'
      path: '/estimate-print/$id'
      fullPath: '/billing/estimate-print/$id'
      preLoaderRoute: typeof BillingEstimatePrintIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/delivery-challans/$id': {
      id: '/billing/delivery-challans/$id'
      path: '/delivery-challans/$id'
      fullPath: '/billing/delivery-challans/$id'
      preLoaderRoute: typeof BillingDeliveryChallansIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/delivery-challan-print/$id': {
      id: '/billing/delivery-challan-print/$id'
      path: '/delivery-challan-print/$id'
      fullPath: '/billing/delivery-challan-print/$id'
      preLoaderRoute: typeof BillingDeliveryChallanPrintIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/debit-notes/$id': {
      id: '/billing/debit-notes/$id'
      path: '/debit-notes/$id'
      fullPath: '/billing/debit-notes/$id'
      preLoaderRoute: typeof BillingDebitNotesIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/debit-note-print/$id': {
      id: '/billing/debit-note-print/$id'
      path: '/debit-note-print/$id'
      fullPath: '/billing/debit-note-print/$id'
      preLoaderRoute: typeof BillingDebitNotePrintIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/credit-notes/$id': {
      id: '/billing/credit-notes/$id'
      path: '/credit-notes/$id'
      fullPath: '/billing/credit-notes/$id'
      preLoaderRoute: typeof BillingCreditNotesIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/credit-note-print/$id': {
      id: '/billing/credit-note-print/$id'
      path: '/credit-note-print/$id'
      fullPath: '/billing/credit-note-print/$id'
      preLoaderRoute: typeof BillingCreditNotePrintIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/workshop/material-slip/$workerId/$date': {
      id: '/workshop/material-slip/$workerId/$date'
      path: '/material-slip/$workerId/$date'
      fullPath: '/workshop/material-slip/$workerId/$date'
      preLoaderRoute: typeof WorkshopMaterialSlipWorkerIdDateRouteImport
      parentRoute: typeof WorkshopRoute
    }
  }
}

interface BillingRouteChildren {
  BillingIdRoute: typeof BillingIdRoute
  BillingNewRoute: typeof BillingNewRoute
  BillingIndexRoute: typeof BillingIndexRoute
  BillingCreditNotePrintIdRoute: typeof BillingCreditNotePrintIdRoute
  BillingCreditNotesIdRoute: typeof BillingCreditNotesIdRoute
  BillingDebitNotePrintIdRoute: typeof BillingDebitNotePrintIdRoute
  BillingDebitNotesIdRoute: typeof BillingDebitNotesIdRoute
  BillingDeliveryChallanPrintIdRoute: typeof BillingDeliveryChallanPrintIdRoute
  BillingDeliveryChallansIdRoute: typeof BillingDeliveryChallansIdRoute
  BillingEstimatePrintIdRoute: typeof BillingEstimatePrintIdRoute
  BillingEstimateIdRoute: typeof BillingEstimateIdRoute
  BillingEstimatesIdRoute: typeof BillingEstimatesIdRoute
  BillingPrintIdRoute: typeof BillingPrintIdRoute
  BillingReceiptIdRoute: typeof BillingReceiptIdRoute
  BillingCreditNotesIndexRoute: typeof BillingCreditNotesIndexRoute
  BillingDebitNotesIndexRoute: typeof BillingDebitNotesIndexRoute
  BillingDeliveryChallansIndexRoute: typeof BillingDeliveryChallansIndexRoute
  BillingEstimatesIndexRoute: typeof BillingEstimatesIndexRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingIdRoute: BillingIdRoute,
  BillingNewRoute: BillingNewRoute,
  BillingIndexRoute: BillingIndexRoute,
  BillingCreditNotePrintIdRoute: BillingCreditNotePrintIdRoute,
  BillingCreditNotesIdRoute: BillingCreditNotesIdRoute,
  BillingDebitNotePrintIdRoute: BillingDebitNotePrintIdRoute,
  BillingDebitNotesIdRoute: BillingDebitNotesIdRoute,
  BillingDeliveryChallanPrintIdRoute: BillingDeliveryChallanPrintIdRoute,
  BillingDeliveryChallansIdRoute: BillingDeliveryChallansIdRoute,
  BillingEstimatePrintIdRoute: BillingEstimatePrintIdRoute,
  BillingEstimateIdRoute: BillingEstimateIdRoute,
  BillingEstimatesIdRoute: BillingEstimatesIdRoute,
  BillingPrintIdRoute: BillingPrintIdRoute,
  BillingReceiptIdRoute: BillingReceiptIdRoute,
  BillingCreditNotesIndexRoute: BillingCreditNotesIndexRoute,
  BillingDebitNotesIndexRoute: BillingDebitNotesIndexRoute,
  BillingDeliveryChallansIndexRoute: BillingDeliveryChallansIndexRoute,
  BillingEstimatesIndexRoute: BillingEstimatesIndexRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface InviteRouteChildren {
  InviteAcceptRoute: typeof InviteAcceptRoute
}

const InviteRouteChildren: InviteRouteChildren = {
  InviteAcceptRoute: InviteAcceptRoute,
}

const InviteRouteWithChildren =
  InviteRoute._addFileChildren(InviteRouteChildren)

interface ReportsRouteChildren {
  ReportsApprovalsRoute: typeof ReportsApprovalsRoute
  ReportsAuditLogRoute: typeof ReportsAuditLogRoute
  ReportsCommunicationAnalyticsRoute: typeof ReportsCommunicationAnalyticsRoute
  ReportsDailyCloseRoute: typeof ReportsDailyCloseRoute
  ReportsDailyGoldFlowRoute: typeof ReportsDailyGoldFlowRoute
  ReportsDeliverySummaryRoute: typeof ReportsDeliverySummaryRoute
  ReportsExceptionsRoute: typeof ReportsExceptionsRoute
  ReportsGoldOutstandingRoute: typeof ReportsGoldOutstandingRoute
  ReportsGoldPositionRoute: typeof ReportsGoldPositionRoute
  ReportsGoldReconciliationRoute: typeof ReportsGoldReconciliationRoute
  ReportsGoldSummaryRoute: typeof ReportsGoldSummaryRoute
  ReportsInventoryAgeingRoute: typeof ReportsInventoryAgeingRoute
  ReportsMonthEndCloseRoute: typeof ReportsMonthEndCloseRoute
  ReportsRemindersRoute: typeof ReportsRemindersRoute
  ReportsVaultReconciliationRoute: typeof ReportsVaultReconciliationRoute
  ReportsWorkerRoute: typeof ReportsWorkerRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReportsDailyclosePrintIdRoute: typeof ReportsDailyclosePrintIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsApprovalsRoute: ReportsApprovalsRoute,
  ReportsAuditLogRoute: ReportsAuditLogRoute,
  ReportsCommunicationAnalyticsRoute: ReportsCommunicationAnalyticsRoute,
  ReportsDailyCloseRoute: ReportsDailyCloseRoute,
  ReportsDailyGoldFlowRoute: ReportsDailyGoldFlowRoute,
  ReportsDeliverySummaryRoute: ReportsDeliverySummaryRoute,
  ReportsExceptionsRoute: ReportsExceptionsRoute,
  ReportsGoldOutstandingRoute: ReportsGoldOutstandingRoute,
  ReportsGoldPositionRoute: ReportsGoldPositionRoute,
  ReportsGoldReconciliationRoute: ReportsGoldReconciliationRoute,
  ReportsGoldSummaryRoute: ReportsGoldSummaryRoute,
  ReportsInventoryAgeingRoute: ReportsInventoryAgeingRoute,
  ReportsMonthEndCloseRoute: ReportsMonthEndCloseRoute,
  ReportsRemindersRoute: ReportsRemindersRoute,
  ReportsVaultReconciliationRoute: ReportsVaultReconciliationRoute,
  ReportsWorkerRoute: ReportsWorkerRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReportsDailyclosePrintIdRoute: ReportsDailyclosePrintIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SettingsRouteChildren {
  SettingsAutomationRoute: typeof SettingsAutomationRoute
  SettingsBranchSettingsRoute: typeof SettingsBranchSettingsRoute
  SettingsCommunicationsRoute: typeof SettingsCommunicationsRoute
  SettingsPrintTemplatesRoute: typeof SettingsPrintTemplatesRoute
  SettingsStorageDiagnosticsRoute: typeof SettingsStorageDiagnosticsRoute
  SettingsWhatsappRoute: typeof SettingsWhatsappRoute
  SettingsWhatsappTemplatesRoute: typeof SettingsWhatsappTemplatesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAutomationRoute: SettingsAutomationRoute,
  SettingsBranchSettingsRoute: SettingsBranchSettingsRoute,
  SettingsCommunicationsRoute: SettingsCommunicationsRoute,
  SettingsPrintTemplatesRoute: SettingsPrintTemplatesRoute,
  SettingsStorageDiagnosticsRoute: SettingsStorageDiagnosticsRoute,
  SettingsWhatsappRoute: SettingsWhatsappRoute,
  SettingsWhatsappTemplatesRoute: SettingsWhatsappTemplatesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StockRouteChildren {
  StockIdRoute: typeof StockIdRoute
  StockImportRoute: typeof StockImportRoute
  StockVerificationRoute: typeof StockVerificationRoute
  StockIndexRoute: typeof StockIndexRoute
  StockPrintIdRoute: typeof StockPrintIdRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockIdRoute: StockIdRoute,
  StockImportRoute: StockImportRoute,
  StockVerificationRoute: StockVerificationRoute,
  StockIndexRoute: StockIndexRoute,
  StockPrintIdRoute: StockPrintIdRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

interface WorkshopRouteChildren {
  WorkshopIdRoute: typeof WorkshopIdRoute
  WorkshopGoldBookRoute: typeof WorkshopGoldBookRoute
  WorkshopWorkerBooksRoute: typeof WorkshopWorkerBooksRoute
  WorkshopIndexRoute: typeof WorkshopIndexRoute
  WorkshopBookJewellerIdRoute: typeof WorkshopBookJewellerIdRoute
  WorkshopFilingsSlipIdRoute: typeof WorkshopFilingsSlipIdRoute
  WorkshopGoldBookPrintWorkerIdRoute: typeof WorkshopGoldBookPrintWorkerIdRoute
  WorkshopReceiveSlipIdRoute: typeof WorkshopReceiveSlipIdRoute
  WorkshopWorkerBookWorkerIdRoute: typeof WorkshopWorkerBookWorkerIdRoute
  WorkshopMaterialSlipWorkerIdDateRoute: typeof WorkshopMaterialSlipWorkerIdDateRoute
}

const WorkshopRouteChildren: WorkshopRouteChildren = {
  WorkshopIdRoute: WorkshopIdRoute,
  WorkshopGoldBookRoute: WorkshopGoldBookRoute,
  WorkshopWorkerBooksRoute: WorkshopWorkerBooksRoute,
  WorkshopIndexRoute: WorkshopIndexRoute,
  WorkshopBookJewellerIdRoute: WorkshopBookJewellerIdRoute,
  WorkshopFilingsSlipIdRoute: WorkshopFilingsSlipIdRoute,
  WorkshopGoldBookPrintWorkerIdRoute: WorkshopGoldBookPrintWorkerIdRoute,
  WorkshopReceiveSlipIdRoute: WorkshopReceiveSlipIdRoute,
  WorkshopWorkerBookWorkerIdRoute: WorkshopWorkerBookWorkerIdRoute,
  WorkshopMaterialSlipWorkerIdDateRoute: WorkshopMaterialSlipWorkerIdDateRoute,
}

const WorkshopRouteWithChildren = WorkshopRoute._addFileChildren(
  WorkshopRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  InviteRoute: InviteRouteWithChildren,
  LedgerRoute: LedgerRoute,
  NotificationsRoute: NotificationsRoute,
  OtpLoginRoute: OtpLoginRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  StockRoute: StockRouteWithChildren,
  VerifyRoute: VerifyRoute,
  WhatsappRoute: WhatsappRoute,
  WorkshopRoute: WorkshopRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  DocTokenRoute: DocTokenRoute,
  PeopleIdRoute: PeopleIdRoute,
  PeopleImportRoute: PeopleImportRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  HardwareIndexRoute: HardwareIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PeopleLedgerPrintIdRoute: PeopleLedgerPrintIdRoute,
  PeoplePrintIdRoute: PeoplePrintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
