// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { supabaseAuthStorage } from "@/lib/auth/auth-storage";
import { createThrottledFetch } from "@/lib/supabase-fetch-throttle";
import { isProductionSupabaseEgressBlocked } from "@/lib/supabase-egress-guard";

const throttledFetch = createThrottledFetch(fetch);
const devEgressQuarantine = isProductionSupabaseEgressBlocked();

function sanitizeEnvValue(value: string | undefined | null): string {
  if (!value) return "";
  let normalized = value.trim();
  if (
    (normalized.startsWith('"') && normalized.endsWith('"')) ||
    (normalized.startsWith("'") && normalized.endsWith("'"))
  ) {
    normalized = normalized.slice(1, -1);
  }
  return normalized.trim();
}

const PROD_SUPABASE_URL = "https://dqgrrafuoxaorvyrcuuh.supabase.co";
const PROD_SUPABASE_KEY = "sb_publishable_nJNeQ0ZIit5jFjK-J2qCMA_wvs8llEN";
const PROD_SUPABASE_PROJECT_ID = "dqgrrafuoxaorvyrcuuh";

function getResolvedConfig() {
  const isBrowser = typeof window !== "undefined";
  const isRemoteDomain = isBrowser && window.location.hostname !== "localhost" && window.location.hostname !== "127.0.0.1";

  // 1. Runtime window / global injection
  const windowEnv = isBrowser ? ((window as any).__ENV__ || (window as any).ENV || {}) : {};

  // 2. LocalStorage override (if explicitly saved by admin)
  let storedUrl = "";
  let storedKey = "";
  let storedProjectId = "";
  if (isBrowser) {
    try {
      const legacyKeys = ["VITE_SUPABASE_URL", "MTJ_SUPABASE_URL", "VITE_SUPABASE_PUBLISHABLE_KEY", "MTJ_SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PROJECT_ID"];
      for (const k of legacyKeys) {
        const val = localStorage.getItem(k);
        if (val && (val.includes("xrvsvzfqjptzbxjscnvf") || val.includes("mtj-erp") || val.includes("0wEt7qew0XI5Ml8fqfVKyw"))) {
          localStorage.removeItem(k);
        }
      }
      storedUrl = localStorage.getItem("VITE_SUPABASE_URL") || localStorage.getItem("MTJ_SUPABASE_URL") || "";
      storedKey = localStorage.getItem("VITE_SUPABASE_PUBLISHABLE_KEY") || localStorage.getItem("MTJ_SUPABASE_PUBLISHABLE_KEY") || "";
      storedProjectId = localStorage.getItem("VITE_SUPABASE_PROJECT_ID") || "";
    } catch {
      // Ignore localStorage access restrictions
    }
  }

  // 3. Build-time environment variable
  const envUrl = sanitizeEnvValue(import.meta.env.VITE_SUPABASE_URL);
  const envKey = sanitizeEnvValue(
    (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
    (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)
  );
  const envProjectId = sanitizeEnvValue(import.meta.env.VITE_SUPABASE_PROJECT_ID);

  let resolvedUrl = sanitizeEnvValue(windowEnv.VITE_SUPABASE_URL) || storedUrl || envUrl;
  let resolvedKey = sanitizeEnvValue(windowEnv.VITE_SUPABASE_PUBLISHABLE_KEY || windowEnv.VITE_SUPABASE_ANON_KEY) || storedKey || envKey;
  let resolvedProjectId = sanitizeEnvValue(windowEnv.VITE_SUPABASE_PROJECT_ID) || storedProjectId || envProjectId;

  // 4. Production Resilience Gate:
  // On remote production domain or if legacy/decommissioned project is referenced,
  // enforce the authoritative production Supabase backend.
  const isDecommissioned =
    resolvedUrl.includes("xrvsvzfqjptzbxjscnvf") ||
    resolvedUrl.includes("mtj-erp") ||
    resolvedKey.includes("0wEt7qew0XI5Ml8fqfVKyw");

  if (
    !resolvedUrl ||
    isDecommissioned ||
    (isRemoteDomain && (resolvedUrl.includes("localhost") || resolvedUrl.includes("127.0.0.1") || resolvedUrl.includes("default") || resolvedUrl !== PROD_SUPABASE_URL))
  ) {
    resolvedUrl = PROD_SUPABASE_URL;
    resolvedKey = PROD_SUPABASE_KEY;
    resolvedProjectId = PROD_SUPABASE_PROJECT_ID;
  }

  if (!resolvedKey) {
    resolvedKey = PROD_SUPABASE_KEY;
  }

  return {
    url: resolvedUrl,
    key: resolvedKey,
    projectId: resolvedProjectId || PROD_SUPABASE_PROJECT_ID,
  };
}

export function isSupabaseConfigured(): boolean {
  const { url, key } = getResolvedConfig();
  return !!url && !!key && (url.startsWith("http://") || url.startsWith("https://"));
}

function createSupabaseClient() {
  const { url: supabaseUrl, key: supabasePublishableKey } = getResolvedConfig();

  if (!supabaseUrl || !supabasePublishableKey) {
    throw new Error(
      `Missing Supabase configuration. VITE_SUPABASE_URL is "${supabaseUrl || ""}", VITE_SUPABASE_PUBLISHABLE_KEY is "${supabasePublishableKey ? "present" : "missing"}". Please check your environment variables or .env file.`,
    );
  }

  if (!supabaseUrl.startsWith("http://") && !supabaseUrl.startsWith("https://")) {
    throw new Error(
      `Invalid Supabase URL: "${supabaseUrl}". Must be a valid HTTP or HTTPS URL. Please check your VITE_SUPABASE_URL environment variable.`,
    );
  }

  return createClient<Database>(supabaseUrl, supabasePublishableKey, {
    auth: {
      storage: typeof window !== "undefined" ? supabaseAuthStorage : undefined,
      persistSession: true,
      // Hourly token refresh against production from localhost was ~347 auth req/min.
      autoRefreshToken: !devEgressQuarantine,
      detectSessionInUrl: true,
    },
    realtime: devEgressQuarantine
      ? { params: { eventsPerSecond: 1 } }
      : undefined,
    global: {
      fetch: (input, init) => {
        const timeoutSignal = AbortSignal.timeout(25_000);
        const signal =
          init?.signal && typeof AbortSignal.any === "function"
            ? AbortSignal.any([init.signal, timeoutSignal])
            : (init?.signal ?? timeoutSignal);
        return throttledFetch(input, { ...init, signal });
      },
    },
  });
}

let supabaseClient: ReturnType<typeof createSupabaseClient> | undefined;

export function getRawSupabaseClient(): ReturnType<typeof createSupabaseClient> {
  if (!supabaseClient) supabaseClient = createSupabaseClient();
  return supabaseClient;
}

export function getSupabaseClient(): ReturnType<typeof createSupabaseClient> {
  return getRawSupabaseClient();
}
