// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function sanitizeEnvValue(value: string | undefined | null): string {
  if (!value) return "";
  let normalized = value.trim();
  if (
    (normalized.startsWith('"') && normalized.endsWith('"')) ||
    (normalized.startsWith("'") && normalized.endsWith("'"))
  ) {
    normalized = normalized.slice(1, -1);
  }
  return normalized.trim();
}

function getResolvedConfig() {
  return {
    url: sanitizeEnvValue(import.meta.env.VITE_SUPABASE_URL),
    key: sanitizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY),
    projectId: sanitizeEnvValue(import.meta.env.VITE_SUPABASE_PROJECT_ID),
  };
}

export function isSupabaseConfigured(): boolean {
  const { url, key } = getResolvedConfig();
  return !!url && !!key && (url.startsWith("http://") || url.startsWith("https://"));
}

function createSupabaseClient() {
  const { url: supabaseUrl, key: supabasePublishableKey } = getResolvedConfig();

  if (!supabaseUrl || !supabasePublishableKey) {
    throw new Error(
      `Missing Supabase configuration. VITE_SUPABASE_URL is "${supabaseUrl || ""}", VITE_SUPABASE_PUBLISHABLE_KEY is "${supabasePublishableKey ? "present" : "missing"}". Please check your environment variables or .env file.`,
    );
  }

  if (!supabaseUrl.startsWith("http://") && !supabaseUrl.startsWith("https://")) {
    throw new Error(
      `Invalid Supabase URL: "${supabaseUrl}". Must be a valid HTTP or HTTPS URL. Please check your VITE_SUPABASE_URL environment variable.`,
    );
  }

  return createClient<Database>(supabaseUrl, supabasePublishableKey, {
    auth: {
      // Keep Supabase as the only auth authority while matching the Product
      // Owner's session rule: stay signed in during the browser session, then
      // expire naturally when the browser/tab session is closed.
      storage: typeof window !== "undefined" ? sessionStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      fetch: (input, init) => {
        const timeoutSignal = AbortSignal.timeout(10_000);
        const signal =
          init?.signal && typeof AbortSignal.any === "function"
            ? AbortSignal.any([init.signal, timeoutSignal])
            : (init?.signal ?? timeoutSignal);
        return fetch(input, { ...init, signal });
      },
    },
  });
}

let supabaseClient: ReturnType<typeof createSupabaseClient> | undefined;

export function getRawSupabaseClient(): ReturnType<typeof createSupabaseClient> {
  if (!supabaseClient) supabaseClient = createSupabaseClient();
  return supabaseClient;
}

export function getSupabaseClient(): ReturnType<typeof createSupabaseClient> {
  return getRawSupabaseClient();
}
