// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { initLocalDb, queryTable, upsertRow, deleteRow, runLocal } from "@/lib/local-db";
import { isOfflineMode, isLocalFirstMode } from "@/lib/deployment-mode";

function sanitizeEnvValue(val: string | undefined | null): string {
  if (!val) return "";
  let s = val.trim();
  if (s.startsWith('"') && s.endsWith('"')) {
    s = s.slice(1, -1);
  }
  if (s.startsWith("'") && s.endsWith("'")) {
    s = s.slice(1, -1);
  }
  return s.trim();
}

/** Runtime Supabase config keys — set by the Setup Wizard (Hybrid mode) so a
 *  customer points the app at their OWN Supabase project without a rebuild.
 *  localStorage override wins over the build-time env/fallbacks. */
export const SUPABASE_RUNTIME_KEYS = {
  url: "supabase_runtime_url",
  key: "supabase_runtime_key",
  projectId: "supabase_runtime_project_id",
} as const;

function runtimeOverride(key: string): string {
  try {
    return typeof localStorage !== "undefined" ? sanitizeEnvValue(localStorage.getItem(key)) : "";
  } catch {
    return "";
  }
}

function getResolvedConfig() {
  // Runtime (Hybrid wizard) override first, then build-time configuration.
  // There is deliberately no embedded customer project: an Offline install
  // must not silently bind itself to Arivahly's or another customer's cloud.
  const rawUrl =
    runtimeOverride(SUPABASE_RUNTIME_KEYS.url) ||
    sanitizeEnvValue(import.meta.env.VITE_SUPABASE_URL);
  const rawKey =
    runtimeOverride(SUPABASE_RUNTIME_KEYS.key) ||
    sanitizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
  const rawProjectId =
    runtimeOverride(SUPABASE_RUNTIME_KEYS.projectId) ||
    sanitizeEnvValue(import.meta.env.VITE_SUPABASE_PROJECT_ID);

  const values = [rawUrl, rawKey, rawProjectId].filter(Boolean);

  let detectedUrl = values.find((v) => v.startsWith("http://") || v.startsWith("https://")) || "";
  let detectedKey =
    values.find((v) => v.startsWith("sb_publishable_") || v.startsWith("eyJ")) || "";

  if (!detectedUrl) {
    detectedUrl =
      values.find((v) => v.includes(".supabase.co") || v.includes("supabase.net")) || "";
  }
  if (!detectedKey) {
    detectedKey = values.find((v) => v.length > 30 && !v.startsWith("http")) || "";
  }

  let detectedProjectId = values.find((v) => v !== detectedUrl && v !== detectedKey) || "";

  if (!detectedUrl) detectedUrl = rawUrl;
  if (!detectedKey) detectedKey = rawKey;
  if (!detectedProjectId) detectedProjectId = rawProjectId;

  return {
    url: detectedUrl,
    key: detectedKey,
    projectId: detectedProjectId,
  };
}

export function isSupabaseConfigured(): boolean {
  const { url, key } = getResolvedConfig();
  if (!url || !key) return false;
  return url.startsWith("http://") || url.startsWith("https://");
}

interface LocalSelectOptions {
  count?: "exact";
  head?: boolean;
}

interface LocalFilter {
  field: string;
  op: string;
  value: unknown;
}

interface LocalOrder {
  field: string;
  ascending: boolean;
}

class LocalQuery {
  table: string;
  action: "select" | "insert" | "upsert" | "update" | "delete" = "select";
  columns: string[] | null = null;
  selectOptions: LocalSelectOptions | undefined;
  filters: LocalFilter[] = [];
  orders: LocalOrder[] = [];
  limitCount?: number;
  payloadRows: any[] = [];
  updatePayload: Record<string, unknown> | null = null;
  ready: Promise<void>;

  constructor(table: string) {
    this.table = table;
    this.ready = initLocalDb();
  }

  select(columns: string, opts?: LocalSelectOptions) {
    this.action = "select";
    this.columns = columns
      .split(",")
      .map((c) => c.trim())
      .filter(Boolean);
    this.selectOptions = opts;
    return this;
  }

  insert(rows: any[] | object) {
    this.action = "insert";
    this.payloadRows = Array.isArray(rows) ? rows : [rows];
    return this;
  }

  upsert(rows: any[] | object) {
    this.action = "upsert";
    this.payloadRows = Array.isArray(rows) ? rows : [rows];
    return this;
  }

  update(patch: Record<string, unknown>) {
    this.action = "update";
    this.updatePayload = patch;
    return this;
  }

  delete() {
    this.action = "delete";
    return this;
  }

  eq(field: string, value: unknown) {
    this.filters.push({ field, op: "eq", value });
    return this;
  }

  neq(field: string, value: unknown) {
    this.filters.push({ field, op: "neq", value });
    return this;
  }

  filter(field: string, op: string, value: unknown) {
    this.filters.push({ field, op, value });
    return this;
  }

  order(field: string, opts: { ascending?: boolean }) {
    this.orders.push({ field, ascending: opts.ascending ?? true });
    return this;
  }

  limit(count: number) {
    this.limitCount = count;
    return this;
  }

  maybeSingle() {
    return this.then(async (result: any) => {
      if (result.error) return result;
      const data = Array.isArray(result.data) ? result.data : [];
      return { data: data.length === 1 ? data[0] : null, error: null };
    });
  }

  single() {
    return this.then(async (result: any) => {
      if (result.error) return result;
      const data = Array.isArray(result.data) ? result.data : [];
      if (data.length === 1) return { data: data[0], error: null };
      if (data.length === 0) return { data: null, error: { message: "No rows returned" } };
      return { data: null, error: { message: "Multiple rows returned" } };
    });
  }

  private normalizeRow(row: Record<string, any>): Record<string, any> {
    const normalized = { ...row };
    if (typeof normalized.data === "string") {
      try {
        normalized.data = JSON.parse(normalized.data);
      } catch {
        // leave as string when JSON parse fails
      }
    }
    return normalized;
  }

  private getFieldValue(row: Record<string, any>, field: string): unknown {
    if (field.includes("->>")) {
      const [root, key] = field.split("->>");
      const raw = row[root];
      if (raw == null) return undefined;
      try {
        const parsed = typeof raw === "string" ? JSON.parse(raw) : raw;
        if (parsed && typeof parsed === "object") {
          return parsed[key] ?? parsed[key.replace(/([A-Z])/g, "_$1").toLowerCase()];
        }
      } catch {
        return undefined;
      }
    }
    if (Object.prototype.hasOwnProperty.call(row, field)) return row[field];
    const camel = field.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
    return Object.prototype.hasOwnProperty.call(row, camel) ? row[camel] : undefined;
  }

  private applyFilters(rows: Record<string, any>[]): Record<string, any>[] {
    return rows.filter((row) => {
      for (const filter of this.filters) {
        const actual = this.getFieldValue(row, filter.field);
        const expected = filter.value;
        if (filter.op === "eq" && actual !== expected) return false;
        if (filter.op === "neq" && actual === expected) return false;
        if (filter.op === "gt" && !(typeof actual === "number" && actual > (expected as number)))
          return false;
        if (filter.op === "lt" && !(typeof actual === "number" && actual < (expected as number)))
          return false;
      }
      return true;
    });
  }

  private applyOrders(rows: Record<string, any>[]): Record<string, any>[] {
    if (!this.orders.length) return rows;
    return [...rows].sort((a, b) => {
      for (const order of this.orders) {
        const aVal = this.getFieldValue(a, order.field);
        const bVal = this.getFieldValue(b, order.field);
        if (aVal === bVal) continue;
        if (aVal == null) return order.ascending ? 1 : -1;
        if (bVal == null) return order.ascending ? -1 : 1;
        if (aVal < bVal) return order.ascending ? -1 : 1;
        if (aVal > bVal) return order.ascending ? 1 : -1;
      }
      return 0;
    });
  }

  private projectRow(row: Record<string, any>): Record<string, any> {
    if (!this.columns || this.columns.length === 0 || this.columns.includes("*")) {
      return this.normalizeRow(row);
    }
    const selected: Record<string, any> = {};
    for (const col of this.columns) {
      selected[col] = this.getFieldValue(this.normalizeRow(row), col);
    }
    return selected;
  }

  private async executeSelect(): Promise<any> {
    const allRows = queryTable(this.table).map(this.normalizeRow.bind(this));
    const filtered = this.applyFilters(allRows);
    const ordered = this.applyOrders(filtered);
    const truncated = this.limitCount != null ? ordered.slice(0, this.limitCount) : ordered;
    const data = truncated.map((row) => this.projectRow(row));
    const result: any = { data, error: null };
    if (this.selectOptions?.count === "exact") {
      result.count = filtered.length;
      if (this.selectOptions.head) {
        result.data = null;
      }
    }
    return result;
  }

  private async executeWrite(): Promise<any> {
    return runLocal(async () => {
      if (this.action === "insert" || this.action === "upsert") {
        for (const row of this.payloadRows) {
          const saved = this.normalizeRow({ ...row });
          upsertRow(this.table, saved);
        }
        return { data: this.payloadRows, error: null };
      }

      if (this.action === "update") {
        const allRows = queryTable(this.table).map(this.normalizeRow.bind(this));
        const candidates = this.applyFilters(allRows);
        const updatedRows: any[] = [];
        for (const row of candidates) {
          const next = { ...row, ...this.updatePayload };
          upsertRow(this.table, next);
          updatedRows.push(next);
        }
        return { data: updatedRows, error: null };
      }

      if (this.action === "delete") {
        const allRows = queryTable(this.table).map(this.normalizeRow.bind(this));
        const candidates = this.applyFilters(allRows);
        for (const row of candidates) {
          deleteRow(this.table, String(row.id));
        }
        return { data: null, error: null };
      }

      return { data: null, error: { message: "Unsupported local write action" } };
    });
  }

  async execute(): Promise<any> {
    await this.ready;
    if (this.action === "select") {
      return this.executeSelect();
    }
    return this.executeWrite();
  }

  then<TResult1 = any, TResult2 = never>(
    onfulfilled?: ((value: any) => TResult1 | PromiseLike<TResult1>) | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null,
  ): Promise<TResult1 | TResult2> {
    return this.execute().then(onfulfilled, onrejected);
  }
}

function createSupabaseClient() {
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = getResolvedConfig();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      `Missing Supabase configuration. VITE_SUPABASE_URL is "${SUPABASE_URL || ""}", VITE_SUPABASE_PUBLISHABLE_KEY is "${SUPABASE_PUBLISHABLE_KEY ? "present" : "missing"}". Please check your environment variables or .env file.`,
    );
  }

  const isValidUrl = SUPABASE_URL.startsWith("http://") || SUPABASE_URL.startsWith("https://");
  if (!isValidUrl) {
    throw new Error(
      `Invalid Supabase URL: "${SUPABASE_URL}". Must be a valid HTTP or HTTPS URL. Please check your VITE_SUPABASE_URL environment variable.`,
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (input, init) => {
        const timeoutSignal = AbortSignal.timeout(10_000);
        const signal =
          init?.signal && typeof AbortSignal.any === "function"
            ? AbortSignal.any([init.signal, timeoutSignal])
            : (init?.signal ?? timeoutSignal);
        return fetch(input, { ...init, signal });
      },
    },
  });
}

let _supabaseClient: ReturnType<typeof createSupabaseClient> | undefined;
let _rawSupabaseClient: ReturnType<typeof createSupabaseClient> | undefined;

export function getRawSupabaseClient(): ReturnType<typeof createSupabaseClient> {
  if (!_rawSupabaseClient) _rawSupabaseClient = createSupabaseClient();
  return _rawSupabaseClient;
}

// The local-db (SQLite via sql.js) read path is Plan 1 Step 2 work — not yet
// wired to any cloud sync/seed mechanism, so an empty local database would
// silently break every `.from()` read (including auth's account lookup) if
// enabled unconditionally. Opt-in only, off by default, until Step 2's sync
// engine actually populates local-db from Supabase. Enable for local
// development/testing via VITE_ENABLE_LOCAL_DB=true.
const LOCAL_DB_READS_ENABLED = import.meta.env.VITE_ENABLE_LOCAL_DB === "true";

/**
 * Offline-mode auth stub (TAD §14, SAD §17: "Offline mode must never require
 * internet"). In Offline deployment mode the local `local_users` table is the
 * only credential store — see src/lib/local-auth.ts. Every supabase.auth call
 * therefore has to resolve locally, with no session and no network: callers
 * see "signed out" and fall through to the local auth path instead of firing
 * a request at the Supabase project.
 */
const OFFLINE_AUTH_ERROR = { message: "Offline mode: cloud authentication is disabled." };

const offlineAuth = {
  getSession: async () => ({ data: { session: null }, error: null }),
  getUser: async () => ({ data: { user: null }, error: null }),
  onAuthStateChange: () => ({
    data: { subscription: { unsubscribe: () => {} } },
  }),
  signOut: async () => ({ error: null }),
  signInWithPassword: async () => ({
    data: { session: null, user: null },
    error: OFFLINE_AUTH_ERROR,
  }),
  signInWithOtp: async () => ({ data: { session: null, user: null }, error: OFFLINE_AUTH_ERROR }),
  signUp: async () => ({ data: { session: null, user: null }, error: OFFLINE_AUTH_ERROR }),
  resetPasswordForEmail: async () => ({ data: null, error: OFFLINE_AUTH_ERROR }),
  updateUser: async () => ({ data: { user: null }, error: OFFLINE_AUTH_ERROR }),
  setSession: async () => ({ data: { session: null, user: null }, error: OFFLINE_AUTH_ERROR }),
  refreshSession: async () => ({ data: { session: null, user: null }, error: OFFLINE_AUTH_ERROR }),
};

export function getSupabaseClient(): ReturnType<typeof createSupabaseClient> {
  if (_supabaseClient) return _supabaseClient;
  const proxy = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
    get(_target, prop) {
      // Decided per call, not at module load: the deployment mode is only
      // known after local-db hydrates, which happens after this module is
      // first imported.
      const localFirst = isLocalFirstMode();
      if (prop === "from" && (isLocalFirstMode() || LOCAL_DB_READS_ENABLED)) {
        return (table: string) => new LocalQuery(table);
      }
      if (localFirst && prop === "auth") return offlineAuth;
      // Every remaining network surface is refused rather than silently
      // reaching the network. Hybrid cloud traffic is owned exclusively by
      // the synchronization provider via getRawSupabaseClient().
      if (localFirst && (prop === "rpc" || prop === "channel")) {
        return () => {
          throw new Error(`Local-first mode: cloud ${String(prop)} is unavailable here.`);
        };
      }
      if (localFirst && (prop === "functions" || prop === "storage" || prop === "realtime")) {
        throw new Error(`Local-first mode: cloud ${String(prop)} is unavailable here.`);
      }
      const cloudClient = getRawSupabaseClient();
      return Reflect.get(cloudClient, prop, cloudClient);
    },
  });
  _supabaseClient = proxy;
  return proxy;
}
